### ISSUE TITLE
New group doesn't appear after re-open "add to group" popup

### ISSUE THREAD

**Issue by HongHT** [topcoder-platform/u-bahn-app#247] opened 2020-07-12 15:02 UTC
**Reproduction Steps:**
1. Open the application
2. Click on any "+" button -> show "Add to group" popup
3. Click on "Search or create popup" textbox -> enter new name group, ex: "666"
4. Click on "Create" button -> show browser alert for success message -> Click on"OK"
5. Click on "Search or create popup" textbox -> Enter "666" then observe
6. Click on "Done" button then re-open "add to group" popup
7. Click on "Search or create popup" textbox -> Enter "666" then observe

**Screenshot/screencast:**
https://drive.google.com/drive/folders/1dsBJQlFvwP3hvWAnUm_WvuhOmAqALuDQ

**Actual Result:**  Step 7: New group "666" doesn't appear after re-open "add to group" popup

**Expected Result:** New group should appear after re-open "add to group" popup

**Device/OS:** Laptop | Windows 10 (64bit)

**Browser Information:** IE11 , Google Chrome 83.0.4103.116, Firefox 78.0.2

**Comment by callmekatootie** [comment] 2020-07-15 14:35
duplicate of #187

**Closed by callmekatootie** 2020-07-15 14:35 UTC
