### ISSUE TITLE
Changing the name from Brady swift to long name is going out of the screen

### ISSUE THREAD

**Issue by Vips19** [topcoder-platform/u-bahn-app#95] opened 2020-07-12 13:40 UTC
Screenshots
![Screenshot (345)](https://user-images.githubusercontent.com/29044523/87247757-4b30e480-c473-11ea-8b52-bf3a7b9cef69.png)

Reproduction Steps:

Open the Application https://skill-search.topcoder-dev.com/
Click Topcoder > Go to first tab
Click Edit User button for Brady Swift and change the name and Observe

Actual Result: the name is going out of the screen

Expected Result: the name is should be properly shown

Device/OS: Laptop | Windows 8.1 (64bit)

Browser Information: IE11,Chrome,Firefox

**Comment by callmekatootie** [comment] 2020-07-15 08:08
duplicate of #91

**Closed by callmekatootie** 2020-07-15 08:08 UTC
