### ISSUE TITLE
Employee details page is not scrollable when clicked on edit icon

### ISSUE THREAD

**Issue by rajanmourya** [topcoder-platform/u-bahn-app#19] opened 2020-07-12 13:09 UTC
**Describe the bug**
Employee details page is not scrollable when clicked on edit icon

**To Reproduce**
1. Go to https://skill-search.topcoder-dev.com/ and login with tonyj /
appirio123
2. Now click on any employee edit icon
3. observe the popped up dialog is not scrollabel

**Actual Behavior**
Employee details popped up dialog is not scrollable

**Expected behavior**
Dialog must be scrollable so the user can veiw all the details
**Screenshots**
![Snapshot 2020-07-12 18 35 36](https://user-images.githubusercontent.com/42939505/87247056-f2f7e380-c46e-11ea-9fdb-871a890a5f2f.png)

**OS/Browser:**
  - OS:  Windows 10 (64 Bit)
 - Browser: Chrome
 - Version:  83.0.4103.116

**Comment by callmekatootie** [comment] 2020-07-15 05:32
duplicate of #17

**Closed by callmekatootie** 2020-07-15 05:32 UTC
