### ISSUE TITLE
Alignment on groups is not correct in the edit talent screen 

### ISSUE THREAD

**Issue by ajithck333** [topcoder-platform/u-bahn-app#53] opened 2020-07-12 13:23 UTC
Device: Laptop

Operating System: Windows 10

Browser:Chrome

Steps to reproduce :

1.	Log in to the https://skill-search.topcoder-dev.com/
2.	Click on the edit talent 
3.	Alignment on groups is not correct 

Actual result:

Alignment on groups is not correct in the edit talent screen 

Expected results: 

Alignment on groups in the edit talent screen should be correct 
[alignment on edit talen screen in groups is not correct.docx](https://github.com/topcoder-platform/u-bahn-app/files/4908560/alignment.on.edit.talen.screen.in.groups.is.not.correct.docx)

**Comment by callmekatootie** [comment] 2020-07-15 07:09
Duplicate of #46

**Closed by callmekatootie** 2020-07-15 07:09 UTC
