### ISSUE TITLE
[$10] When hovering over the cross button mouse icon is not getting changed to hand icon (to show the user it is clickable)

### ISSUE THREAD

**Issue by rajanmourya** [topcoder-platform/u-bahn-app#285] opened 2020-07-12 15:28 UTC
**Describe the bug**
When hovering over the cross button mouse icon is not getting changed to hand icon (to show the user it is clickable)

**To Reproduce**
1. Go to https://skill-search.topcoder-dev.com/
2. Now click on edit profile
3. Now go custom attributes
4. Now click on any field and observe the cross icon
5. Now hover over that and observe the mouse icon is not getting changed to hand icon

**Actual Behavior**
Pointer icon is not getting changed when hover over cross icon in text field

**Expected behavior**
Pointer icon must change so the user will know it is clickable

**Screenshots**
[2020-07-12 19-41-38.zip](https://github.com/topcoder-platform/u-bahn-app/files/4908758/2020-07-12.19-41-38.zip)

**OS/Browser:**
  - OS:  Windows 10 (64 Bit)
 - Browser: IE 11
 - Version:  11.900

**Comment by callmekatootie** [comment] 2020-07-17 14:52
The cross icon here is coming from IE itself and not from the app.

Will take this as a bug to remove it instead

**Comment by callmekatootie** [comment] 2020-07-21 10:31
Expected: In the edit profile modal, in IE11, for the input fields (of the user's attributes), remove the (X) icon that IE11 automatically shows for input fields

**Comment by cwdcwd** [comment] 2020-07-24 07:43
Contest https://www.topcoder.com/challenges/30134113 has been created for this ticket.<br/><br/>```This is an automated message for lazybaer via Topcoder X```

**Comment by cwdcwd** [comment] 2020-07-24 09:38
Contest https://www.topcoder.com/challenges/30134113 has been updated - it has been assigned to Timor.<br/><br/>```This is an automated message for lazybaer via Topcoder X```

**Comment by marioskranitsas** [comment] 2020-07-24 10:39
@callmekatootie can I please work on this? I cannot self-assign.

**Comment by cwdcwd** [comment] 2020-07-24 12:05
Contest https://www.topcoder.com/challenges/30134113 has been updated - it has been assigned to genycopedison.<br/><br/>```This is an automated message for lazybaer via Topcoder X```

**Comment by phongnt** [comment] 2020-07-24 12:12
@callmekatootie I could not reproduce on develop branch now, because of reset button is not shown in custom attributes.

![image](https://user-images.githubusercontent.com/759326/88389818-6a1f6700-cde1-11ea-8395-15a6fdca028f.png)

**Comment by marioskranitsas** [comment] 2020-07-24 12:21
Hi @phongnt, as you can see I have requested from the copilot to work on this issue as I'm not able to self-assign. Please respect the rules and do not pick issues that someone else is working on. Thank you!
cc @callmekatootie

**Comment by phongnt** [comment] 2020-07-24 12:34
@marioskranitsas Sorry, I missed your comment. Unassigned.

**Comment by cwdcwd** [comment] 2020-07-24 14:39
Contest https://www.topcoder.com/challenges/30134113 has been updated - it has been assigned to marioskranitsas.<br/><br/>```This is an automated message for lazybaer via Topcoder X```

**Comment by callmekatootie** [comment] 2020-07-24 14:39
@marioskranitsas You have been added to the group. You can assign yourself now

**Comment by callmekatootie** [comment] 2020-07-24 14:40
But let me check if this issue still exists in IE11 or not...

**Comment by marioskranitsas** [comment] 2020-07-24 14:41
PR: https://github.com/topcoder-platform/u-bahn-app/pull/577

**Comment by callmekatootie** [comment] 2020-07-24 14:42
Confirmed - issue does still exist in IE11

**Comment by callmekatootie** [comment] 2020-07-24 14:42
*Yet to check your PR

**Comment by cwdcwd** [comment] 2020-07-24 15:47
Payment task has been updated: https://software.topcoder.com/review/actions/ViewProjectDetails?pid=30134113<br/><br/>```This is an automated message for lazybaer via Topcoder X```

**Closed** 2020-07-24 15:47 UTC
Labels: bug, low priority, tcx_Assigned, tcx_FixAccepted
