### ISSUE TITLE
Group name with only space characters are getting created successfully

### ISSUE THREAD

**Issue by rprakash20** [topcoder-platform/u-bahn-app#404] opened 2020-07-12 19:32 UTC
### Steps to Reproduce

1. Open “https://skill-search.topcoder-dev.com/“  app
2. Login with tonyj /appirio123
3. Select topcoder as organization
4. navigate to groups tab
5. type in multiple spaces in the 'Search or create group' text box
6. Click on Create
7. 

### Screenshots or Screen Capture

<img width="1440" alt="Screenshot 2020-07-13 at 12 57 43 AM" src="https://user-images.githubusercontent.com/5712602/87254929-16895100-c4a4-11ea-8faa-cccac3c488b5.png">
<img width="1440" alt="Screenshot 2020-07-13 at 12 58 20 AM" src="https://user-images.githubusercontent.com/5712602/87254932-1b4e0500-c4a4-11ea-83e4-c7026ba9144b.png">

[spaces_group_name.mov.zip](https://github.com/topcoder-platform/u-bahn-app/files/4909288/spaces_group_name.mov.zip)

### Current Results
Group name with only spaces are getting created successfully. An alert shows up saying "Group with name                created successfully."

### Expected Results
Group name should have a validation for name and group must not be created if user has entered only spaces in the group name field.

### Browser version and OS version
- Device: MacBook Pro 13 inch
- Browser: Chrome Version 83.0.4103.116 (Official Build) (64-bit)
- OS Version: macOS Catalina 10.15.4

**Comment by callmekatootie** [comment] 2020-07-17 08:36
duplicate of #34

**Closed by callmekatootie** 2020-07-17 08:36 UTC
