### ISSUE TITLE
Stuck when create group with same name

### ISSUE THREAD

**Issue by g1tman** [topcoder-platform/u-bahn-app#106] opened 2020-07-12 13:43 UTC
## Steps to Reproduce

    1. Open the URL https://skill-search.topcoder-dev.com/ and login
    2. Select some filter and get results
    3. Click plus button to add groups for some user
    4. Let it load
    5. In search box enter "Avengers" (There was already a group of that name)
    6. Click on create button

## Screenshots/Video
![Screenshot from 2020-07-12 19-13-31](https://user-images.githubusercontent.com/32861951/87247829-cbefe080-c473-11ea-8f85-7f44e73654d7.png)

##  Actual Result(s)

Button stuck on "creating...".

##  Expected Result(s)

Should display error that group exists already

##  Environment Details

    Browser(s): Firefox 78.0.1 (64-bit)

**Comment by callmekatootie** [comment] 2020-07-15 08:13
duplicate of #93

**Closed by callmekatootie** 2020-07-15 08:13 UTC
