### ISSUE TITLE
inconsistency of words being used while selecting group loading group users, or after loading

### ISSUE THREAD

**Issue by akultalwar89** [topcoder-platform/u-bahn-app#276] opened 2020-07-12 15:20 UTC
Steps to reproduce
• 1. Go to application-https://skill-search.topcoder-dev.com/
• 2. click on group page button -inconsistency of words being used while selecting group loading group users, or after loading

Current results
inconsistency of words being used while selecting group loading group users, or after loading

Expected results
it should either say user, or member, or profile. 

• Browser version: Chrome: Version 83.0.4103.116
• OS version : Macbook Air , Catalina 10.15.2
Screen shots -
[Screen Recording 2020-07-12 at 8.48.39 PM.mov.zip](https://github.com/topcoder-platform/u-bahn-app/files/4908747/Screen.Recording.2020-07-12.at.8.48.39.PM.mov.zip)

**Comment by callmekatootie** [comment] 2020-07-16 15:21
duplicate of #211

**Closed by callmekatootie** 2020-07-16 15:21 UTC
