### ISSUE TITLE
Popup background is visible

### ISSUE THREAD

**Issue by Vips19** [topcoder-platform/u-bahn-app#48] opened 2020-07-12 13:22 UTC
screenshots
![Screenshot (340)](https://user-images.githubusercontent.com/29044523/87247317-ca70e900-c470-11ea-8991-4f2b3d8ea54a.png)

Reproduction Steps:

Open the Application https://skill-search.topcoder-dev.com/
Click Topcoder > Go to first tab
Click Add Filters button in left side nav

Actual Result: Tathe background is visble behind the popup

Expected Result: Background shouldn't be visible

Device/OS: Laptop | Windows 8.1 (64bit)

Browser Information: IE11,Chrome,Firefox

**Comment by callmekatootie** [comment] 2020-07-15 07:04
Duplicate of #39

**Closed by callmekatootie** 2020-07-15 07:04 UTC
