### ISSUE TITLE
Ui Issue in edit user Page

### ISSUE THREAD

**Issue by Citra-citoru** [topcoder-platform/u-bahn-app#275] opened 2020-07-12 15:20 UTC
## Step To Reproduce
1. Go to https://skill-search.topcoder-dev.com/
2. Login as ToniJ(topcoder)
3. Click edit button in one of the cards. (I choose Jonathan Lueilwitz)

## Expected Result
Every word should be wrap and there is no text-overflow.

## Actual Result
Text overflow shown

## Screenshot
![](https://www.dropbox.com/s/a3y2z4nza00s1cc/ui_issue.png?raw=1)

## Device/OS/Browser Information:
a. Device: Lenovo (laptop)
Processor : AMD A9-9420 RADEON R5, 5  Compute Cores 2C+3G 3.00 GHz
RAM : 8 GB
System Type: 64 Bit OS, x64-based processor
Pen or touch: no pen or touch
b. OS: Windows 10 Home Single Language
c. Browser: Chrome Version 83.0.4103.106 (Official Build) (64-bit)

**Comment by callmekatootie** [comment] 2020-07-16 15:19
duplicate of #46

**Closed by callmekatootie** 2020-07-16 15:19 UTC
