### ISSUE TITLE
[$30] Unable to edit general form fields while clicked on blank space of respective label 

### ISSUE THREAD

**Issue by bhattashubham** [topcoder-platform/u-bahn-app#305] opened 2020-07-12 15:44 UTC
**Reproduction Steps:** 

Open the Application https://skill-search.topcoder-dev.com/
Click Topcoder > Go to tab 01
click on edit on profile card 
clear all text in form field and save 
again click on same contact card and try to edit fields of general form fields

**Actual Result:**  unable to edit while clicked on blank space 

**Expected Result:** edit box should open while clicked on blank space of respective label or border should be present to edit box 

**Device/OS:** Laptop / Windows 10

**Browser Information:** Chrome 83.0.4103.116 
![bug4](https://user-images.githubusercontent.com/48902251/87250734-bcc65e00-c486-11ea-9566-63164d4829ee.jpg)

![Device_info](https://user-images.githubusercontent.com/48902251/87250737-c2bc3f00-c486-11ea-8862-a5663d16b7fa.png)

**Comment by callmekatootie** [comment] 2020-07-16 15:46
Not a bug - the design keeps it at a distance

**Comment by callmekatootie** [comment] 2020-07-16 15:46
On second thoughts, will take it as a bug - we can focus on the input in this case

**Comment by callmekatootie** [comment] 2020-07-21 10:42
Expected:

When the user clicks on the label or the space between the label and the input box - for all inputs in that modal (name, location etc - even the custom attributes), focus on the respective input field

**Comment by cwdcwd** [comment] 2020-07-23 07:18
Contest https://www.topcoder.com/challenges/30133970 has been created for this ticket.<br/><br/>```This is an automated message for lazybaer via Topcoder X```

**Comment by cwdcwd** [comment] 2020-07-23 11:42
Contest https://www.topcoder.com/challenges/30133970 has been updated - it has been assigned to Timor.<br/><br/>```This is an automated message for lazybaer via Topcoder X```

**Comment by cwdcwd** [comment] 2020-07-23 15:45
Payment task has been updated: https://software.topcoder.com/review/actions/ViewProjectDetails?pid=30133970<br/><br/>```This is an automated message for lazybaer via Topcoder X```

**Closed** 2020-07-23 15:45 UTC
Labels: bug, low priority, tcx_Assigned, tcx_FixAccepted
