### ISSUE TITLE
Padding issue for tiles in edit profile

### ISSUE THREAD

**Issue by Vips19** [topcoder-platform/u-bahn-app#59] opened 2020-07-12 13:26 UTC
Screenshots
![Screenshot (341)](https://user-images.githubusercontent.com/29044523/87247372-1d4aa080-c471-11ea-8904-ae6c51290906.png)

Reproduction Steps:

1. Open the Application https://skill-search.topcoder-dev.com/
2. Click Topcoder > Go to first tab
3. Click Edit button for Aang Airbender

Actual Result: Observe the side tiles under GROUP, Padding is not proper

Expected Result: Paddign should be proper for tiles

Device/OS: Laptop | Windows 8.1 (64bit)

Browser Information: IE11,Chrome,Firefox

**Comment by callmekatootie** [comment] 2020-07-15 07:26
duplicate of #46

**Closed by callmekatootie** 2020-07-15 07:26 UTC
