### ISSUE TITLE
Company Logo partial visible

### ISSUE THREAD

**Issue by g1tman** [topcoder-platform/u-bahn-app#338] opened 2020-07-12 16:29 UTC
## Steps to Reproduce

    1. Open the URL https://skill-search.topcoder-dev.com/ and login
    2. See top left logo

## Screenshots/Video
![Screenshot from 2020-07-12 21-57-55](https://user-images.githubusercontent.com/32861951/87251661-f1d4af80-c48a-11ea-99ab-5021e6e4b392.png)

##  Actual Result(s)

Response message

In firefox, Logo doesnt show fully. (On chrome, it works)

##  Expected Result(s)

Logo should be fully visible

##  Environment Details

    Browser(s): Firefox 78.0.1 (64-bit)

**Comment by callmekatootie** [comment] 2020-07-17 15:09
Cannot reproduce

**Comment by g1tman** [comment] 2020-07-17 16:47
@callmekatootie 

Still able to reproduce this.

Even the link of svg shows partial logo. I suspect there is some sort of ambiguity in svg which leads to different rendering on different browser. (On chrome it does appear fully)

![Screenshot from 2020-07-17 22-06-00](https://user-images.githubusercontent.com/32861951/87810016-f2e65200-c879-11ea-9a6d-bcdf4728dc72.png)

However, when I download the svg from the link, and open it in image viewer, it does appear fully. And when I open this image with firefox, again its displayed partially.

I think it relates to this issue - https://stackoverflow.com/questions/12830897/svg-renders-but-gets-cut-off-in-firefox-only-why
I dont know if the solutions there work.

I found that in the svg file increasing the width to 26mm made the logo fully visible.

**Comment by callmekatootie** [comment] 2020-07-17 18:17
Thank you for that - I am able to see the issue now by directly viewing the image and I understand that this could be an issue later too.

**Comment by wdprice** [comment] 2020-07-20 18:47
@callmekatootie Update from "U-Bahn" to Topcoder logo while resolving please.

**Comment by callmekatootie** [comment] 2020-07-21 10:50
@wdprice Ok - can you kindly share the logo that I need to replace with.

Also - should the title be updated to Topcoder Employee skills search portal? (The website title - in the title bar I mean)

**Comment by wdprice** [comment] 2020-07-21 17:09
@callmekatootie 
https://zeroheight.com/1g0pfacwv/p/56600f-logos--icons/b/68b761/i/686483

**Comment by callmekatootie** [comment] 2020-07-25 06:16
Resolved.

**Closed by callmekatootie** 2020-07-25 06:16 UTC
Labels: bug, medium priority
