### ISSUE TITLE
Should show "No users found. Try applying a different filter." when enter some spaces inside "Search talent or keyword" box

### ISSUE THREAD

**Issue by HongHT** [topcoder-platform/u-bahn-app#334] opened 2020-07-12 16:23 UTC
**Reproduction Steps:**
1. Open the application 
2. Enter some spaces inside "Search talent or keyword" box 
3. Click enter keyboard and observe the result.

**Screenshot/screencast:**
https://drive.google.com/drive/folders/1Nkanu5LKltRZNo2ieHWNKSyg6-zcrDbe?fbclid=IwAR2pD3gYGvZcsncY7T4ewgF1IEi-61WkcDjy_Rs7N6WIH86KnWvGCSpOFdU

**Actual Result:** Still show value although only enter some spaces

**Expected Result:** Should show "No users found. Try applying a different filter." when enter some spaces  

**Device/OS:** Laptop | Windows 10 (64bit)

**Browser Information:** IE11 , Google Chrome 83.0.4103.116, Firefox 78.0.2

**Comment by callmekatootie** [comment] 2020-07-17 15:05
Valid bug. Deactivated users show up in the group results...

**Comment by callmekatootie** [comment] 2020-07-17 16:01
duplicate of #150

**Closed by callmekatootie** 2020-07-17 16:01 UTC
Labels: bug
