### ISSUE TITLE
ui issue while entering long username 

### ISSUE THREAD

**Issue by karthikbecse** [topcoder-platform/u-bahn-app#101] opened 2020-07-12 13:42 UTC
Steps to reproduce
• 1. Go to application-https://crm-benefits-prototype.herokuapp.com/pharmacy
• 2. select user click edit 
  3.enter user name as Aang ddsffffffffffffffffffffffffffffffffffffffAang ddsffffffffffffffffffffffffffffffffffffffAang ddsffffffffffffffffffffffffffffffffffffff Airbender
 4, observe 

Current results
overlap with groups 

Expected results
should show properly 

• Browser version: Chrome: Version 83.0.4103.116
• OS version : Windows 10
Screen shots
![bandicam 2020-07-12 19-07-05-479](https://user-images.githubusercontent.com/3225433/87247796-9fd45f80-c473-11ea-8a9d-464326c18388.jpg)

**Comment by callmekatootie** [comment] 2020-07-15 08:11
duplicate of #99

**Closed by callmekatootie** 2020-07-15 08:11 UTC
