### ISSUE TITLE
Searching invalid data will reduce the height of the popup in "Add to Group" but not in "Add Filters"

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/u-bahn-app#336] opened 2020-07-12 16:27 UTC
https://take.ms/GTJqO

**Reproduction Steps:**

1. Open the Application https://skill-search.topcoder-dev.com/
2. Click Topcoder > Go to the Tab 01 (Search)
3. Click Add Filters and Enter 'sadasdasdasd' to the search and check the height of the popup (Height won't reduce)
3. Click Add to Group and Enter 'sadasdasdasd' to the search and check the height of the popup (Height reduced)

**Actual Result:** Searching invalid data will reduce the height of the popup in "Add to Group" but not in "Add Filters"

**Expected Result:** Function should be the same in both locations

**Device/OS:** Laptop | Windows 10 (64bit)

**Browser Information:** IE11

**Comment by callmekatootie** [comment] 2020-07-17 15:08
Could not reproduce but will take it as a bug. In IE11 - the modal height does expand a lot and hides the buttons at the bottom too but in both cases

**Comment by callmekatootie** [comment] 2020-09-30 15:26
After discussion on Slack - Will not be fixed. Closing

**Closed by callmekatootie** 2020-09-30 15:26 UTC
Labels: bug, wontfix
