### ISSUE TITLE
Add to Group window expands while hitting multiple spaces

### ISSUE THREAD

**Issue by bhattashubham** [topcoder-platform/u-bahn-app#372] opened 2020-07-12 17:56 UTC
**Reproduction Steps:** 

Open the Application https://skill-search.topcoder-dev.com/
Click Topcoder > Go to tab 02
Click on edit icon 
click on + icon 
now hit multiple Space
Observe

**Actual Result:** Add to Group window expands while hitting multiple Space

**Expected Result:** window should not change the size on hitting Space

**Device/OS:** Laptop / Windows 10

**Browser Information:** 
![IE_details](https://user-images.githubusercontent.com/48902251/87253270-ab3a8180-c499-11ea-84de-d3cd99347b46.png)

Bug video: https://drive.google.com/file/d/1VRlnC2aryiWuZH73frLgKkNiQCFY8UQ2/view?usp=sharing

**Comment by callmekatootie** [comment] 2020-07-17 16:06
duplicate of #336

**Closed by callmekatootie** 2020-07-17 16:06 UTC
