### ISSUE TITLE
X icon placement issue in Custom attributes fields 

### ISSUE THREAD

**Issue by bhattashubham** [topcoder-platform/u-bahn-app#371] opened 2020-07-12 17:51 UTC
**Reproduction Steps:** 

Open the Application https://skill-search.topcoder-dev.com/
Click Topcoder > Go to tab 01
Click on edit icon 
click on custom attributes 
Observe

**Actual Result:**  X icon is in center of form field  

**Expected Result:**  icon should be on right side of form field 

**Device/OS:** Laptop / Windows 10

**Browser Information:** 
![IE_details](https://user-images.githubusercontent.com/48902251/87253185-d96b9180-c498-11ea-829c-a4012efe463f.png)

![bug12](https://user-images.githubusercontent.com/48902251/87253181-d40e4700-c498-11ea-892d-71d75b316503.jpg)

**Comment by callmekatootie** [comment] 2020-07-17 16:05
need to remove it - duplicate of #285

**Closed by callmekatootie** 2020-07-17 16:05 UTC
