### ISSUE TITLE
[Bug Hunt] Type Error when creating Groups from Main Create Button

### ISSUE THREAD

**Issue by greenmug-md** [topcoder-platform/u-bahn-app#498] opened 2020-07-14 03:31 UTC
<img width="1194" alt="Screenshot 2020-07-14 at 9 00 52 AM" src="https://user-images.githubusercontent.com/34758872/87380652-8edd3880-c5b0-11ea-9a7d-14c9de141ae4.png">

Reproduction Steps:
	1.	Open the Application https://skill-search.topcoder-dev.com/
	2.	Click Topcoder > Go to the Tab 02 (Groups)
	3.	Click on “My Groups” ,
	4.	Create a Group with “d”
	5.	It shows TypeError in console and the console shows “Creating” and is stuck
	
Expected Result: Group should be created 

Device/OS: Laptop | MACOS  (64bit)
Browser Information: Chrome 83.0.4103.116 | Firefox 78.0.2 | IE11

**Comment by callmekatootie** [comment] 2020-07-17 13:22
duplicate of #61

**Closed by callmekatootie** 2020-07-17 13:22 UTC
