### ISSUE TITLE
[$10] Space between search field and Create button 

### ISSUE THREAD

**Issue by g1tman** [topcoder-platform/u-bahn-app#455] opened 2020-07-13 10:26 UTC
## Steps:

	1. Go to https://skill-search.topcoder-dev.com/ and login
	2. Go to second tab (Groups tab)

## Actual Result:

	Firefox -> No gap between search text field and "Create" button

	Chrome -> Space between those.

## Expected Result:
	
	Same interface for both browser. No space between them looks better 

## Screenshot/Video:
Chrome
![Screenshot from 2020-07-13 15-52-48](https://user-images.githubusercontent.com/32861951/87294364-488cc880-c521-11ea-819a-d106f149f858.png)

Firefox
![Screenshot from 2020-07-13 15-53-00](https://user-images.githubusercontent.com/32861951/87294365-49bdf580-c521-11ea-8502-4f76671c8455.png)

	
Browser: Firefox 78.0.1 (64-bit), Chrome Version 83.0.4103.116 (Official Build) (64-bit)

**Comment by callmekatootie** [comment] 2020-07-17 10:56
valid bug

**Comment by wdprice** [comment] 2020-07-20 18:30
I actually like the space better myself.

**Comment by callmekatootie** [comment] 2020-07-21 10:54
Expected: In all browsers, display the gap between the search text and the CREATE button

**Comment by cwdcwd** [comment] 2020-07-23 07:18
Contest https://www.topcoder.com/challenges/30133975 has been created for this ticket.<br/><br/>```This is an automated message for lazybaer via Topcoder X```

**Comment by cwdcwd** [comment] 2020-07-23 09:29
Contest https://www.topcoder.com/challenges/30133975 has been updated - it has been assigned to PkDurlabhji.<br/><br/>```This is an automated message for lazybaer via Topcoder X```

**Comment by PrakashDurlabhji** [comment] 2020-07-23 17:56
@callmekatootie it is already working fine

**Comment by callmekatootie** [comment] 2020-07-23 18:01
@PrakashDurlabhji  Issue exists in Firefox. Did you check there...

**Comment by PrakashDurlabhji** [comment] 2020-07-23 20:33
<img width="960" alt="Capture" src="https://user-images.githubusercontent.com/28830240/88335993-d94d7a80-cd51-11ea-93af-4e71d8890bdc.PNG">

**Comment by PrakashDurlabhji** [comment] 2020-07-23 20:33
@callmekatootie yes

**Comment by callmekatootie** [comment] 2020-07-24 06:33
![image](https://user-images.githubusercontent.com/2317133/88366035-96b58d80-cda5-11ea-9391-4351a3419ebd.png)

This is what I see in Firefox...

I am unassigning this so that somebody else that can reproduce the issue can pick it up

**Comment by cwdcwd** [comment] 2020-07-24 06:34
Contest https://www.topcoder.com/challenges/30133975 has been updated - it has been assigned to Timor.<br/><br/>```This is an automated message for lazybaer via Topcoder X```

**Comment by romitgithub** [comment] 2020-07-24 07:23
@callmekatootie  It's hard to reproduce this. I see everything perfect.

Can you share more details. Like browser, resolution, screen. That would help in finding the bug. Thanks

**Comment by callmekatootie** [comment] 2020-07-24 07:31
Browser: Firefox 78
Resolution: 1920x1080
OS: Ubuntu

**Comment by romitgithub** [comment] 2020-07-24 07:37
Not able to reproduce. Releasing this.

**Comment by cwdcwd** [comment] 2020-07-24 10:04
Contest https://www.topcoder.com/challenges/30133975 has been updated - it has been assigned to vibhash_19.<br/><br/>```This is an automated message for lazybaer via Topcoder X```

**Comment by cwdcwd** [comment] 2020-07-24 15:48
Payment task has been updated: https://software.topcoder.com/review/actions/ViewProjectDetails?pid=30133975<br/><br/>```This is an automated message for lazybaer via Topcoder X```

**Closed** 2020-07-24 15:48 UTC
Labels: bug, low priority, tcx_Assigned, tcx_FixAccepted
