### ISSUE TITLE
When group is name is large it is not showing proper on user details page

### ISSUE THREAD

**Issue by rajanmourya** [topcoder-platform/u-bahn-app#97] opened 2020-07-12 13:40 UTC
**Describe the bug**
When group is name is large it is not showing proper on user details page

**To Reproduce**
1. Go to https://skill-search.topcoder-dev.com/
2. Now click on any user edit icon and observe
3. if the group name is large then margins are not proper from the block

**Actual Behavior**
if the group name is large then margins are not proper from the block

**Expected behavior**
Margin must be constant although group name is large or small

**Screenshots**
![Snapshot 2020-07-12 18 35 36](https://user-images.githubusercontent.com/42939505/87247774-669bef80-c473-11ea-898d-79f52e0e9ac9.png)

**OS/Browser:**
  - OS:  Windows 10 (64 Bit)
 - Browser: Chrome
 - Version:  83.0.4103.116

**Comment by callmekatootie** [comment] 2020-07-15 08:09
duplicate of #46

**Closed by callmekatootie** 2020-07-15 08:09 UTC
