### ISSUE TITLE
UI issue on the CUSTOM ATTRIBUTES tags

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/u-bahn-app#272] opened 2020-07-12 15:18 UTC
![image](https://user-images.githubusercontent.com/42398485/87250193-e18be880-c428-11ea-8020-42973749d391.png)

**Reproduction Steps:**

1. Open the Application https://skill-search.topcoder-dev.com/
2. Click Topcoder > Go to the Tab 01
3. Click "Add Filters" and Turn ON all the filters
4. Edit a profile and add the location as United Kingdom of Great Britain and Northern Ireland
5. Enter Location=United Kingdom of Great Britain and Northern Ireland

 This applied to all the CUSTOM ATTRIBUTES fields with long names

**Actual Result:** UI issue on the CUSTOM ATTRIBUTES tags

**Expected Result:** Should display proper spacing from top and bottom

**Device/OS:** Laptop | Windows 10 (64bit)

**Browser Information:** Chrome 83.0.4103.116 | Firefox 78.0.2 | IE11

**Comment by callmekatootie** [comment] 2020-07-16 15:13
need to check if primary attributes should be allowed under custom attributes filter

**Comment by callmekatootie** [comment] 2020-07-17 14:50
Duplicate of #85

**Closed by callmekatootie** 2020-07-17 14:50 UTC
