### ISSUE TITLE
[Bug Hunt] Group name is not displayed properly.

### ISSUE THREAD

**Issue by CreeyaSean** [topcoder-platform/u-bahn-app#107] opened 2020-07-12 13:45 UTC
Steps to reproduce:
1. Go to URL https://skill-search.topcoder-dev.com/ and login with valid credentials.
2. Navigate tp the second tab.
3. Scroll down to "Taas - Front End Developers" and click on it.
4. Click on edit icon of any profile shown.
5. Observe the groups section.

Actual results:
Under " groups" section "Taas - Front End Developers" is not displayed with proper padding.

Expected results:
All the groups should be displayed properly with correct padding.

Browser version: Chrome: Version 83.0.4103.116

OS version : 

Screen shots:
![4](https://user-images.githubusercontent.com/57211549/87247880-2a1dc300-c476-11ea-8d8b-e5257a0e0e9e.png)

login credential:
tonyj / appirio123

**Comment by callmekatootie** [comment] 2020-07-15 08:14
duplicate of #46

**Closed by callmekatootie** 2020-07-15 08:14 UTC
