### ISSUE TITLE
[Bug Hunt]When user logs out a blank page is displayed with "OK" text

### ISSUE THREAD

**Issue by komal123s** [topcoder-platform/u-bahn-app#235] opened 2020-07-12 14:55 UTC
Steps:
1.Navigate to https://skill-search.topcoder-dev.com/
2.Click on Logout button
![image](https://user-images.githubusercontent.com/68163678/87249568-7caead80-c47d-11ea-8c62-3566c4f459e3.png)
3.Verify blank page with "OK" text.
![image](https://user-images.githubusercontent.com/68163678/87249583-93550480-c47d-11ea-8598-ac79d04bc199.png)
Actual result:
Blank page with OK text
Expected result:
Logout page should be displayed with proper content
Device/Browser:
Laptop
Google Chrome(Version 83.0.4103.116)
OS:Windows 10

**Comment by komal123s** [comment] 2020-07-12 18:22
Data Used:
tonyj\appirio123

**Comment by callmekatootie** [comment] 2020-07-15 14:24
duplicate of #86

**Closed by callmekatootie** 2020-07-15 14:24 UTC
