### ISSUE TITLE
New group is not displayed on the 'Add to Group' popup when user open it again

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/u-bahn-app#410] opened 2020-07-12 19:41 UTC
https://take.ms/1YOCJ

**Reproduction Steps:**

1. Open the Application https://skill-search.topcoder-dev.com/
2. Click Topcoder > Go to the Tab 02 (Group)
3. Select a group and click Edit profile and create a new group and assign the profile to it
4. Now open the 'Add to Group' popup and observe

**Actual Result:** New group is not displayed on the 'Add to Group' popup when the user open it again

**Expected Result:** Should display the new group name

**Device/OS:** Laptop | Windows 10 (64bit)

**Browser Information:** Chrome 83.0.4103.116 | Firefox 78.0.2 | IE11

**Comment by callmekatootie** [comment] 2020-07-17 10:14
duplicate of #187

**Closed by callmekatootie** 2020-07-17 10:14 UTC
