### ISSUE TITLE
Logout dropdowwn is not closed when clicked outside the section

### ISSUE THREAD

**Issue by Vips19** [topcoder-platform/u-bahn-app#73] opened 2020-07-12 13:30 UTC
Screenshots
![Screenshot (343)](https://user-images.githubusercontent.com/29044523/87247494-c85b5a00-c471-11ea-8bf2-1bebf2f83058.png)

Reproduction Steps:

Open the Application https://skill-search.topcoder-dev.com/
Click Topcoder > Go to first tab
Click Top right dropdown for User.
Now click outside the section and Observe the dropdown is not closed

Actual Result: The dropdown is not closed on clicking outside 

Expected Result: Dropdown should be closed on clicking outside the section

Device/OS: Laptop | Windows 8.1 (64bit)

Browser Information: IE11,Chrome,Firefox

**Comment by callmekatootie** [comment] 2020-07-15 07:39
i'll take this as a bug - need to update help text to indicate support for xlsx

**Comment by callmekatootie** [comment] 2020-07-16 15:31
wrong ticket - this is a duplicate of #45

**Closed by callmekatootie** 2020-07-16 15:31 UTC
Labels: bug
