### ISSUE TITLE
X icon overlaps the text in Custom attributes

### ISSUE THREAD

**Issue by bhattashubham** [topcoder-platform/u-bahn-app#351] opened 2020-07-12 16:58 UTC
**Reproduction Steps:** 

Open the Application https://skill-search.topcoder-dev.com/
Click Topcoder > Go to tab 01
Click o edit icon scroll down 
input long name in location field  
click on text box 
Observe 

**Actual Result:** X icon overlaps the text in the location field 

**Expected Result:** X icon should not overlap the text 

**Device/OS:** Laptop / Windows 10

**Browser Information:** IE11  
![IE_details](https://user-images.githubusercontent.com/48902251/87252227-0e73e600-c491-11ea-874d-058b16fd4756.png)

**Comment by bhattashubham** [comment] 2020-07-12 16:58
bug video : https://drive.google.com/file/d/1uhuevcSL-gKJ2oL_J3GKrkYc2rDn7BUG/view?usp=sharing

**Comment by callmekatootie** [comment] 2020-07-17 16:03
Need to remove the X icon - duplicate of #285

**Closed by callmekatootie** 2020-07-17 16:03 UTC
