### ISSUE TITLE
Any Value under Edit User General Option with long data is going out of screen and also in popup

### ISSUE THREAD

**Issue by Vips19** [topcoder-platform/u-bahn-app#103] opened 2020-07-12 13:43 UTC
screenshots
![Screenshot (346)](https://user-images.githubusercontent.com/29044523/87247811-b4185c80-c473-11ea-8c1e-317930c40eaa.png)
![Screenshot (347)](https://user-images.githubusercontent.com/29044523/87247820-c09cb500-c473-11ea-82d5-1386e1124945.png)

Reproduction Steps:

Open the Application https://skill-search.topcoder-dev.com/
Click Topcoder > Go to first tab
Click Edit User button for Brady Swift and Change any General fields value with long value and Observe 

Actual Result: the result is going out of the screen

Expected Result: the results fileds  should be properly shown

Device/OS: Laptop | Windows 8.1 (64bit)

Browser Information: IE11,Chrome,Firefox

**Comment by callmekatootie** [comment] 2020-07-15 08:12
duplicate of #99

**Closed by callmekatootie** 2020-07-15 08:12 UTC
