### ISSUE TITLE
UI issue on the profile card

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/u-bahn-app#105] opened 2020-07-12 13:43 UTC
![image](https://user-images.githubusercontent.com/42398485/87247828-c8c90600-c41b-11ea-9cbe-58b9a4dc4dcc.png)

**Reproduction Steps:**

1. Open the Application https://skill-search.topcoder-dev.com/
2. Click Topcoder > Go to tab 01
3. Check the last profile card
4. Observe

**Actual Result:** UI issue on the profile card

**Expected Result:** Should display the layout properly

**Device/OS:** Laptop | Windows 10 (64bit)

**Browser Information:** Chrome 83.0.4103.116 | Firefox 78.0.2 | IE11

**Comment by callmekatootie** [comment] 2020-07-15 08:13
duplicate of #91

**Closed by callmekatootie** 2020-07-15 08:13 UTC
