### ISSUE TITLE
There is no hover color for filter button

### ISSUE THREAD

**Issue by Citra-citoru** [topcoder-platform/u-bahn-app#287] opened 2020-07-12 15:29 UTC
## Step To Reproduce
1. Go to https://skill-search.topcoder-dev.com/
2. Login as ToniJ(topcoder)
3. Scroll until you found **+ filter** button

## Expected Result
There is a light-grey color appear when we hover the filter button

## Actual Result
There is no light-grey color appear when we hover the filter button

## Screenshot
![](https://www.dropbox.com/s/bsmydddao1wos4r/filter_color.png?raw=1)

## Video
https://www.dropbox.com/s/iyp5g579x8x9k0h/U-Bahn%20employee%20skills%20search%20portal%20-%20Google%20Chrome%202020-07-12%2018-26-38.mp4?dl=0

## Device/OS/Browser Information:
a. Device: Lenovo (laptop)
Processor : AMD A9-9420 RADEON R5, 5  Compute Cores 2C+3G 3.00 GHz
RAM : 8 GB
System Type: 64 Bit OS, x64-based processor
Pen or touch: no pen or touch
b. OS: Windows 10 Home Single Language
c. Browser: Chrome Version 83.0.4103.106 (Official Build) (64-bit)

**Comment by callmekatootie** [comment] 2020-07-16 15:34
duplicate of #188

**Closed by callmekatootie** 2020-07-16 15:34 UTC
