### ISSUE TITLE
[Bug Hunt] User name displayed over the "General" section in edit page.

### ISSUE THREAD

**Issue by CreeyaSean** [topcoder-platform/u-bahn-app#137] opened 2020-07-12 13:57 UTC
Steps to reproduce:
1. Go to URL https://skill-search.topcoder-dev.com/ and login with valid credentials.
login credential:
tonyj / appirio123 
2. Click on edit icon of the profile.
3. Enter very long text in "Last Name" section and save.
4. Now click on the edit icon and observe.

Actual results:
Other information such as "First Name" is hidden by the long text.

Expected results:
One information should not block any other user information.

Browser version: Chrome: Version 83.0.4103.116

Screen shots:
![8](https://user-images.githubusercontent.com/57211549/87248194-d57b4780-c477-11ea-9c29-54688a856e4a.png)

**Comment by callmekatootie** [comment] 2020-07-15 10:50
duplicate of #91

**Closed by callmekatootie** 2020-07-15 10:50 UTC
