### ISSUE TITLE
[Bug Hunt]When user clicks on Add Filter button then Cancel  and Done button are hidden

### ISSUE THREAD

**Issue by komal123s** [topcoder-platform/u-bahn-app#308] opened 2020-07-12 15:49 UTC
**Steps:**
1.Navigate to https://skill-search.topcoder-dev.com/
2.Scroll down and click on Add filter button.
![image](https://user-images.githubusercontent.com/68163678/87250766-e67e8580-c484-11ea-88b9-1faf31c857bd.png)

3.Verify "Cancel" and "Done" buttons are hidden
![image](https://user-images.githubusercontent.com/68163678/87250805-0dd55280-c485-11ea-9f19-301336b115aa.png)

**Actual result:**
"Cancel" and "Done" buttons are hidden
**Expected result:**
"Cancel" and "Done" buttons should not be hidden

**Device/Browser/OS:**
Laptop
Google Chrome(Version 83.0.4103.116)
Windows10

**Comment by komal123s** [comment] 2020-07-12 18:19
Data Used:
tonyj\appirio123

**Comment by callmekatootie** [comment] 2020-07-17 05:02
duplicate of #17

**Closed by callmekatootie** 2020-07-17 05:02 UTC
