### ISSUE TITLE
[$30] In add filter dialog, the toggle buttons are not consistent, they are getting toggled automatically when searched

### ISSUE THREAD

**Issue by rajanmourya** [topcoder-platform/u-bahn-app#141] opened 2020-07-12 14:00 UTC
**Describe the bug**
In add filter dialog, the toggle buttons are not consistent, they are getting toggled automatically when searched

**To Reproduce**
1. Go to https://skill-search.topcoder-dev.com/
2. Now click on add filter
3. now toggle on any filter
4. now search that filter you just toggled on
5. observe the filter is toggled off now

**Actual Behavior**
the filter is getting toggled automatically when they are searched

**Expected behavior**
The filter should not toggle automatically, it should be done by user

**Screenshots**
[2020-07-12 18-48-57.zip](https://github.com/topcoder-platform/u-bahn-app/files/4908610/2020-07-12.18-48-57.zip)

**OS/Browser:**
  - OS:  Windows 10 (64 Bit)
 - Browser: Chrome
 - Version:  83.0.4103.116

**Comment by callmekatootie** [comment] 2020-07-15 10:52
valid bug. good catch.

**Comment by callmekatootie** [comment] 2020-07-21 09:08
Expected - the toggle state of the filter should not change based on what is being searched

**Comment by cwdcwd** [comment] 2020-07-23 10:56
Contest https://www.topcoder.com/challenges/30134027 has been created for this ticket.<br/><br/>```This is an automated message for lazybaer via Topcoder X```

**Comment by bappa90** [comment] 2020-07-23 12:13
@cwdcwd I am not able to assign can you please assign it to me

**Comment by kavinkuma6** [comment] 2020-07-23 12:15
Yes, We are all waiting, we need access to assign. Please provide access to assign ourselves.

**Comment by callmekatootie** [comment] 2020-07-23 12:38
Sorry - but are you all facing the same issue during registration through that link?

**Comment by cwdcwd** [comment] 2020-07-23 12:44
Contest https://www.topcoder.com/challenges/30134027 has been updated - it has been assigned to Nam-NNG.<br/><br/>```This is an automated message for lazybaer via Topcoder X```

**Comment by callmekatootie** [comment] 2020-07-24 12:21
@hoangnam2261 Any updates here - if you are not able to resolve this soon, I may have to open it for others to work on

**Comment by callmekatootie** [comment] 2020-07-25 03:37
This ticket is now open for pickup

**Comment by cwdcwd** [comment] 2020-07-25 03:38
Contest https://www.topcoder.com/challenges/30134027 has been updated - it has been assigned to XnivaXhzne.<br/><br/>```This is an automated message for lazybaer via Topcoder X```

**Comment by cwdcwd** [comment] 2020-07-25 04:40
Contest https://www.topcoder.com/challenges/30134027 has been updated - it has been assigned to genycopedison.<br/><br/>```This is an automated message for lazybaer via Topcoder X```

**Comment by phongnt** [comment] 2020-07-25 04:49
@callmekatootie I could not reproduce this issue on develop branch now

![image](https://user-images.githubusercontent.com/759326/88448911-c4b1d500-ce6c-11ea-88f7-2a4061e1b661.png)

**Comment by phongnt** [comment] 2020-07-25 05:05
@callmekatootie I reproduced now

**Comment by cwdcwd** [comment] 2020-07-25 16:31
Payment task has been updated: https://software.topcoder.com/review/actions/ViewProjectDetails?pid=30134027<br/><br/>```This is an automated message for lazybaer via Topcoder X```

**Closed** 2020-07-25 16:31 UTC
Labels: bug, high priority, tcx_Assigned, tcx_FixAccepted
