### ISSUE TITLE
Page edit User Doesnt Have Close Button

### ISSUE THREAD

**Issue by Citra-citoru** [topcoder-platform/u-bahn-app#90] opened 2020-07-12 13:38 UTC
## Step To Reproduce
1. https://skill-search.topcoder-dev.com/
2. Login as ToniJ(topcoder)
3. Click edit button at the right top of the user card.

## Expected Result
User edit page has a close button

## Actual Result
User edit page doesn't have a close button

## Screenshot
![](https://www.dropbox.com/s/66g9e01wbz0acwe/close_button.png?raw=1)

## Video
https://www.dropbox.com/s/aoejljftbuui452/U-Bahn%20employee%20skills%20search%20portal%20-%20Google%20Chrome%202020-07-12%2016-34-19.mp4?dl=0

## Device/OS/Browser Information:
a. Device: Lenovo (laptop)
Processor : AMD A9-9420 RADEON R5, 5  Compute Cores 2C+3G 3.00 GHz
RAM : 8 GB
System Type: 64 Bit OS, x64-based processor
Pen or touch: no pen or touch
b. OS: Windows 10 Home Single Language
c. Browser: Chrome Version 83.0.4103.106 (Official Build) (64-bit)

**Comment by callmekatootie** [comment] 2020-07-15 08:04
duplicate of #17

**Closed by callmekatootie** 2020-07-15 08:04 UTC
