### ISSUE TITLE
"Create" button should disable when no changes

### ISSUE THREAD

**Issue by HongHT** [topcoder-platform/u-bahn-app#94] opened 2020-07-12 13:39 UTC
**Reproduction Steps:**
1. Open the application 
2. On "Search" tab, click on "+" icon inside any profiles 
3. Observe "Create" button 

**Screenshot/screencast:**
https://drive.google.com/drive/folders/17YP2SCpHwN2zVHs_JQ5guKE6lLzOyv5R?fbclid=IwAR2NLQCT8AejdTQ9aDSlXabD8M5IW869wRbo-BctGSiDpqO43YeKWRGNfg0

**Actual Result:** "Create" button still enabled and user can click on it although no changes

**Expected Result:** "Create" button should disable when no changes 

**Device/OS:** Laptop | Windows 10 (64bit)

**Browser Information:** IE11 , Google Chrome 83.0.4103.116, Firefox 78.0.2

**Comment by callmekatootie** [comment] 2020-07-15 08:07
duplicate of #21

**Closed by callmekatootie** 2020-07-15 08:07 UTC
