### ISSUE TITLE
[Bug Hunt]Sort by drop down remain in same page,until page is refreshed

### ISSUE THREAD

**Issue by ab668685** [topcoder-platform/u-bahn-app#444] opened 2020-07-13 09:24 UTC
Browser : Chrome Version 83.0.4103.116 
Windows -10
Laptop 
Steps to reproduce :-
 1. URL : https://skill-search.topcoder-dev.com/
 2. Login using tonyj / appirio123
 3. Select topcoder .
4. Click on Sort by.
5. View the dropdown
6. Goto next page.

Issue : Sort by drop down remain in same page,until page is refreshed

Expected Result : Sort by drop down should hide when different page is clicked.

![image](https://user-images.githubusercontent.com/61318135/87288064-791c3480-c518-11ea-8674-504049b8283d.png)

**Comment by callmekatootie** [comment] 2020-07-17 10:48
duplicate of #365

**Closed by callmekatootie** 2020-07-17 10:48 UTC
