### ISSUE TITLE
Search Talent For Keyword Sonme Part Is Hiding

### ISSUE THREAD

**Issue by devsreekrishna** [topcoder-platform/u-bahn-app#24] opened 2020-07-12 13:12 UTC
1. Go To https://skill-search.topcoder-dev.com/

2. Select Topcoder

3. See The Search Field & Observe.

4. See Screenshot:-
![1](https://user-images.githubusercontent.com/42583358/87247085-37837f00-c46f-11ea-8b01-e8d68cca8402.png)

5. Current Result:- Search Talent For Keyword Some Part Is Hiding

6. Expected Result:- Search Talent For Keyword Some Part Should Show Fully

7. Browser Version:- Google Chrome Version 83.0.4103.116 (Official Build) (64-bit)

8. OS Version:- macOS High Sierra Version 10.13.6 (17G12034)

**Comment by callmekatootie** [comment] 2020-07-15 05:46
Cannot reproduce. Most likely low resolution, which would be duplicate of #17

**Comment by devsreekrishna** [comment] 2020-07-15 08:40
Hi
This Is different From #17 & kindly Find The Attachment To Verify Above Issue.

[1.mp4.zip](https://github.com/topcoder-platform/u-bahn-app/files/4923952/1.mp4.zip)
![1](https://user-images.githubusercontent.com/42583358/87523547-b281ab00-c6a4-11ea-988c-4c6a02de6a5a.png)

Thanks

**Comment by callmekatootie** [comment] 2020-07-15 15:12
Will take a second look

**Comment by callmekatootie** [comment] 2020-07-17 14:12
I am afraid I cannot reproduce this. I feel it is identical to #17 in that your resolution seems to be too less.

**Closed by callmekatootie** 2020-07-17 14:12 UTC
