### ISSUE TITLE
Arrow direction remains same when Logout is displayed upon click on user name.

### ISSUE THREAD

**Issue by coderkid19** [topcoder-platform/u-bahn-app#284] opened 2020-07-12 15:27 UTC
Steps:
1)Login to portal https://skill-search.topcoder-dev.com/ with tonyj/appirio123  ( selected Org topcoder)
2) Click on logged in user
3) Logout is displayed
4) Observe arrow next to user name

Current Result :
Arrow direction remains same when Logout is displayed upon click on user name.

Expected result:
Arrow direction should be changed when Logout is displayed upon click on user name.

Latest Firefox
Windows 10

**Comment by coderkid19** [comment] 2020-07-12 15:27
![25](https://user-images.githubusercontent.com/51490878/87250439-58090480-c482-11ea-9038-25b527f09339.png)

![Chrome_Version_83 0 4103 116](https://user-images.githubusercontent.com/51490878/87250441-5b03f500-c482-11ea-934a-8b3f462e5f07.png)

**Comment by coderkid19** [comment] 2020-07-12 15:28
![Chrome_Version_83 0 4103 116](https://user-images.githubusercontent.com/51490878/87250448-648d5d00-c482-11ea-9e2e-6d7279ad4909.png)

**Comment by callmekatootie** [comment] 2020-07-16 15:29
duplicate of #88

**Comment by callmekatootie** [comment] 2020-07-16 15:33
reopening - #88 is about filter... need to check if there's a ticket that talks about the dropdown...

**Comment by callmekatootie** [comment] 2020-07-17 15:58
Couldn't find one. Keeping this as a valid bug

**Comment by callmekatootie** [comment] 2020-07-17 17:43
Found it - #65

**Closed by callmekatootie** 2020-07-17 17:43 UTC
Labels: bug
