### ISSUE TITLE
Location Tooltips are missing

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/u-bahn-app#437] opened 2020-07-13 06:29 UTC
https://take.ms/R0ifQ

**Reproduction Steps:**

1. Open the Application https://skill-search.topcoder-dev.com/
2. Click Topcoder > Go to the Tab 01 (Search)
3. Click More from Locations
4. Hover over the trimmed location names

**Actual Result:** Location Tooltips are missing

**Expected Result:** Should display the tooltips because user can see the long trimmed names

**Device/OS:** Laptop | Windows 10 (64bit)

**Browser Information:**  IE11

**Comment by callmekatootie** [comment] 2020-07-17 15:25
duplicate of #128

**Closed by callmekatootie** 2020-07-17 15:25 UTC
