### ISSUE TITLE
While Clicking On Edit Group Logo Is Not Showing Properly

### ISSUE THREAD

**Issue by devsreekrishna** [topcoder-platform/u-bahn-app#342] opened 2020-07-12 16:40 UTC
1. Go To https://skill-search.topcoder-dev.com/

2. Select Topcoder

3. Click On Edit Icon Then Observe.

4. See Screencast & Screenshot:-
[20.mp4.zip](https://github.com/topcoder-platform/u-bahn-app/files/4908852/20.mp4.zip)
![20](https://user-images.githubusercontent.com/42583358/87251850-547a7b00-c48c-11ea-8e86-f25ea99a91fb.png)

5. Current Result:- While Clicking On Edit Group Logo Is Not Showing Properly

6. Expected Result:- While Clicking On Edit Group Logo Should Show Properly

7. Browser Version:- Google Chrome Version 83.0.4103.116 (Official Build) (64-bit)

8. OS Version:- macOS High Sierra Version 10.13.6 (17G12034)

**Comment by callmekatootie** [comment] 2020-07-17 07:33
duplicate of #17

**Closed by callmekatootie** 2020-07-17 07:33 UTC
