### ISSUE TITLE
[$20] While Creating Large Number Group Letters Are Going Outside Box

### ISSUE THREAD

**Issue by devsreekrishna** [topcoder-platform/u-bahn-app#281] opened 2020-07-12 15:23 UTC
1. Go To https://skill-search.topcoder-dev.com/

2. Select Topcoder

3. Click On Icon Next To Filter

4. Click On Search Or Create Group then Type Large number & Click Create.

5. Click OK & Scroll Down Mouse To Below Then Observe.

6. See Screencast & Screenshot:-
[13.mp4.zip](https://github.com/topcoder-platform/u-bahn-app/files/4908749/13.mp4.zip)
![13](https://user-images.githubusercontent.com/42583358/87250291-80443380-c481-11ea-96da-067ee6e5ac49.png)

7. Current Result:- While Creating Large Number Group Letters Are Going Outside Box

8. Expected Result:- While Creating Large Number Group Letters Should Not Go Outside Box

9. Browser Version:- Google Chrome Version 83.0.4103.116 (Official Build) (64-bit)

10. OS Version:- macOS High Sierra Version 10.13.6 (17G12034)

**Comment by callmekatootie** [comment] 2020-07-16 15:27
duplicate of #29

**Comment by devsreekrishna** [comment] 2020-07-16 16:20
Hi
Kindly Observe It Closely Then Decide In My Case Its Going Outside Of Box But In #29 Its Within Box.
Thanks

**Comment by callmekatootie** [comment] 2020-07-17 17:59
Makes sense. Valid bug - I see that this one does not have a space and thus it spills out

**Comment by cwdcwd** [comment] 2020-07-24 07:45
Contest https://www.topcoder.com/challenges/30134117 has been created for this ticket.<br/><br/>```This is an automated message for lazybaer via Topcoder X```

**Comment by cwdcwd** [comment] 2020-07-24 07:45
Contest https://www.topcoder.com/challenges/30134117 has been updated - it has been assigned to Timor.<br/><br/>```This is an automated message for lazybaer via Topcoder X```

**Comment by callmekatootie** [comment] 2020-07-24 15:46
@romitgithub In IE11, the fix is not working:

![image](https://user-images.githubusercontent.com/2317133/88409719-f7b78280-cdf2-11ea-94d4-730e0eca7f91.png)

**Comment by romitgithub** [comment] 2020-07-24 16:11
@callmekatootie Using **break-all** is alright?

**Comment by romitgithub** [comment] 2020-07-24 16:16
Updated PR

**Comment by callmekatootie** [comment] 2020-07-25 06:47
Yes - break-all should be fine

**Comment by cwdcwd** [comment] 2020-07-25 17:02
Payment task has been updated: https://software.topcoder.com/review/actions/ViewProjectDetails?pid=30134117<br/><br/>```This is an automated message for lazybaer via Topcoder X```

**Closed** 2020-07-25 17:02 UTC
Labels: bug, low priority, tcx_Assigned, tcx_FixAccepted
