### ISSUE TITLE
[BugHunt] Add Filter- Enabling/disabling the filter while applying search is not working

### ISSUE THREAD

**Issue by Jacksug** [topcoder-platform/u-bahn-app#421] opened 2020-07-13 04:22 UTC
Steps:
1.Navigate to https://skill-search.topcoder-dev.com/

2.Login with credentials

3.Click on Add Profile

4. Search for keyword "Avail". 

5. Enable the toggle if its disabled/ disable the toggle if its enabled

6. Enabling/disabling is not getting reflected in the Filter panel

Actual result:
Enabling/disabling is not getting reflected in the Filter panel

Expected result:
Enabling/disabling should get reflected in the Filter panel

ScreenCast:

[FilterPanel_Search.zip](https://github.com/topcoder-platform/u-bahn-app/files/4910593/FilterPanel_Search.zip)

Device/Browser/OS:
Laptop
Chrome(Version 83.0.4103.116 (Official Build) (64-bit))
Windows10

Login credential used:
tonyj\appirio123

**Comment by callmekatootie** [comment] 2020-07-17 10:24
duplicate of #141

**Closed by callmekatootie** 2020-07-17 10:24 UTC
