### ISSUE TITLE
[$10] Error Occured on double click on "Download template"

### ISSUE THREAD

**Issue by g1tman** [topcoder-platform/u-bahn-app#359] opened 2020-07-12 17:19 UTC
## Steps to Reproduce

    1. Open the URL https://skill-search.topcoder-dev.com/ and login
    2. Let it load
    3. Go to Bulk upload tab (Tab 3)
    4. Double click on "Download Import Template (.XLS)"

## Screenshots/Video
[sc15.zip](https://github.com/topcoder-platform/u-bahn-app/files/4908925/sc15.zip)
![Screenshot from 2020-07-12 22-48-38](https://user-images.githubusercontent.com/32861951/87252576-dfaa3f80-c491-11ea-92cc-c922f25c2e82.png)

##  Actual Result(s)

Displays error (See screenshot)

##  Expected Result(s)

Should not result in any error

##  Environment Details

    Browser(s): Firefox 78.0.1 (64-bit)

**Comment by callmekatootie** [comment] 2020-07-17 07:47
cannot reproduce

**Comment by g1tman** [comment] 2020-07-17 11:34
@callmekatootie For Chrome, I can reproduce with a different steps. Not sure what causes the issue.

1. Open Bulk upload tab
2. Double click on the "Download Import Template (.XLS)" and press ESC key.

However, this is a unlikely scenario. But firefox issue is of more concern.

**Comment by callmekatootie** [comment] 2020-07-17 16:28
Yes I tried in Firefox.

On chrome I tried the steps you mentioned and I did get the error. However, I think it is a valid error - the request was aborted and thus the message

**Comment by g1tman** [comment] 2020-07-17 16:30
@callmekatootie  But shouldnt we get the download started atleast. In firefox, download doesnt even start.

**Comment by callmekatootie** [comment] 2020-07-17 16:31
Not sure about that but as I understand, the error that you get, in your scenario is perfectly valid

**Comment by g1tman** [comment] 2020-07-17 16:34
@callmekatootie

When someone wants to download, they may mistakenly double click the link. That would lead to this error.
I dont think user should be taken to this error page. They should be served with the content.

Like when click download link on some website twice, you still are served with content.

**Comment by callmekatootie** [comment] 2020-07-18 07:07
Ok - I checked what's up. Double clicking results in the browser cancelling the first request on its own (and hence you see the error).

I will take this as a bug to prevent double click of the link

**Comment by callmekatootie** [comment] 2020-07-21 10:52
Expected: Ignore double clicks on the Download Template link

**Comment by cwdcwd** [comment] 2020-07-23 07:18
Contest https://www.topcoder.com/challenges/30133977 has been created for this ticket.<br/><br/>```This is an automated message for lazybaer via Topcoder X```

**Comment by cwdcwd** [comment] 2020-07-23 12:59
Contest https://www.topcoder.com/challenges/30133977 has been updated - it has been assigned to gauravseta.<br/><br/>```This is an automated message for lazybaer via Topcoder X```

**Comment by cwdcwd** [comment] 2020-07-24 05:55
Contest https://www.topcoder.com/challenges/30133977 has been updated - it has been assigned to Nam-NNG.<br/><br/>```This is an automated message for lazybaer via Topcoder X```

**Comment by cwdcwd** [comment] 2020-07-25 05:02
Contest https://www.topcoder.com/challenges/30133977 has been updated - it has been assigned to kingszlayer.<br/><br/>```This is an automated message for lazybaer via Topcoder X```

**Comment by callmekatootie** [comment] 2020-07-25 16:19
@venkygot  Status check - if you are not actively working on this at the moment, request you to kindly open for others to pickup

**Comment by cwdcwd** [comment] 2020-07-25 16:57
Contest https://www.topcoder.com/challenges/30133977 has been updated - it has been assigned to genycopedison.<br/><br/>```This is an automated message for lazybaer via Topcoder X```

**Comment by cwdcwd** [comment] 2020-07-26 17:21
Payment task has been updated: https://software.topcoder.com/review/actions/ViewProjectDetails?pid=30133977<br/><br/>```This is an automated message for lazybaer via Topcoder X```

**Closed** 2020-07-26 17:21 UTC
Labels: bug, medium priority, tcx_Assigned, tcx_FixAccepted
