### ISSUE TITLE
Groups are not aligned properly or the groups container doesn't have proper padding in the Edit Member UI

### ISSUE THREAD

**Issue by rprakash20** [topcoder-platform/u-bahn-app#57] opened 2020-07-12 13:25 UTC
### Steps to Reproduce

1. Open https://skill-search.topcoder-dev.com/ web app
2. Login with tonyj /appirio123
3. Click on Edit icon on any of the user
4. Notice the Groups box shown on this page

### Screenshots or Screen Capture
<img width="1440" alt="Screenshot 2020-07-12 at 6 52 34 PM" src="https://user-images.githubusercontent.com/5712602/87247382-2d628000-c471-11ea-8ef6-709ddc8cfa76.png">

[Screen Recording 2020-07-12 at 6.53.50 PM.zip](https://github.com/topcoder-platform/u-bahn-app/files/4908561/Screen.Recording.2020-07-12.at.6.53.50.PM.zip)

### Current Results
Groups are not aligned properly or the groups container doesn't have proper padding in the Edit Member UI

### Expected Results
the groups container should have proper padding as it in the main page

### Browser version and OS version
- Device: MacBook Pro 13 inch
- Browser: Chrome Version 83.0.4103.116 (Official Build) (64-bit)
- OS Version: macOS Catalina 10.15.4

**Comment by rprakash20** [comment] 2020-07-12 13:27
<img width="1440" alt="Screenshot 2020-07-12 at 6 55 56 PM" src="https://user-images.githubusercontent.com/5712602/87247414-597e0100-c471-11ea-8840-da0be31e7ee8.png">

**Comment by callmekatootie** [comment] 2020-07-15 07:11
duplicate of #46

**Closed by callmekatootie** 2020-07-15 07:11 UTC
