### ISSUE TITLE
[$30] Pressing backspace in Custom attributes fields is throwing error 

### ISSUE THREAD

**Issue by bhattashubham** [topcoder-platform/u-bahn-app#392] opened 2020-07-12 18:45 UTC
**Reproduction Steps:** 

Open the Application https://skill-search.topcoder-dev.com/
Click Topcoder > Go to tab 01
Click click on edit icon 
not go to Custom attributes feild and 
input long name which goes over the X icon
now press backspace and observe

**Actual Result:** shows error Can’t reach this page

**Expected Result:** hitting backspace shouldn't show error page 

**Device/OS:** Laptop / Windows 10

**Browser Information:** 
![IE_details](https://user-images.githubusercontent.com/48902251/87254196-7978e900-c4a0-11ea-83c4-a6f71e59b0f0.png)

bug video: https://drive.google.com/file/d/1iavpItMW5jznbAmR43v3sVcYJpV7DMiR/view?usp=sharing

**Comment by callmekatootie** [comment] 2020-07-17 15:22
valid bug

**Comment by callmekatootie** [comment] 2020-07-24 07:41
Expected:

Type a long text in the input and then press backspace - there's an error. Expected that pressing backspace does not display the error and only erases the text

**Comment by cwdcwd** [comment] 2020-07-24 07:43
Contest https://www.topcoder.com/challenges/30134112 has been created for this ticket.<br/><br/>```This is an automated message for lazybaer via Topcoder X```

**Comment by cwdcwd** [comment] 2020-07-24 10:06
Contest https://www.topcoder.com/challenges/30134112 has been updated - it has been assigned to _ckd.<br/><br/>```This is an automated message for lazybaer via Topcoder X```

**Comment by kodar007** [comment] 2020-07-25 03:27
@cwdcwd on investigating i found that input dom is not being updated on ie 11 while it's updating on chrome. I will try adding babel polyfill to fix this

**Comment by callmekatootie** [comment] 2020-07-25 03:41
@kodar007 Thanks for the update

**Comment by kodar007** [comment] 2020-07-25 07:30
@callmekatootie releasing this as it would take more time for me.
the issue is not related to polyfill, but components re-rending and input element getting out of focus on ie 11

**Comment by cwdcwd** [comment] 2020-07-25 09:19
Contest https://www.topcoder.com/challenges/30134112 has been updated - it has been assigned to Suman-953556.<br/><br/>```This is an automated message for lazybaer via Topcoder X```

**Comment by Giri-Suman** [comment] 2020-07-25 18:58
@cwdcwd i have invested lot of time but not able to reproduce the issue. I have tried more than 10 times but only 1 time i got this error

**Comment by callmekatootie** [comment] 2020-07-25 19:00
No worries - you can try to work on this for couple more hours or you could open it for others to pickup

**Comment by Giri-Suman** [comment] 2020-07-25 19:00
[bandicam 2020-07-26 00-26-29-765.zip](https://github.com/topcoder-platform/u-bahn-app/files/4976221/bandicam.2020-07-26.00-26-29-765.zip)

**Comment by Giri-Suman** [comment] 2020-07-25 19:04
@callmekatootie can you please again whether its a valid bug or not

**Comment by callmekatootie** [comment] 2020-07-26 17:32
@Giri-Suman This is indeed a valid bug - opening for others to work on in case they are able to reproduce it and can find a solution

**Comment by cwdcwd** [comment] 2020-07-26 17:34
Contest https://www.topcoder.com/challenges/30134112 has been updated - it has been assigned to cagdas001.<br/><br/>```This is an automated message for lazybaer via Topcoder X```

**Comment by cagdas001** [comment] 2020-07-26 23:07
@callmekatootie I can't reproduce either Maybe this is not a valid bug anymore, with latest updates?

**Comment by callmekatootie** [comment] 2020-07-27 02:28
So this happens only in IE11 - type a long text and press and hold backspace after that to erase all the text. When you press and hold backspace, the text gets erased - about 4-5 characters and then this error occurs

**Comment by cwdcwd** [comment] 2020-07-27 03:06
Contest https://www.topcoder.com/challenges/30134112 has been updated - it has been assigned to kingszlayer.<br/><br/>```This is an automated message for lazybaer via Topcoder X```

**Comment by phongnt** [comment] 2020-07-27 06:31
> So this happens only in IE11 - type a long text and press and hold backspace after that to erase all the text. When you press and hold backspace, the text gets erased - about 4-5 characters and then this error occurs

@callmekatootie I reproduced on IE successful. It's valid bug. I fixed also. But let @venkygot try to fix firstly. Please assign me if @venkygot can not fix this. Thanks

**Comment by callmekatootie** [comment] 2020-07-27 06:32
@venkygot Are you actively working on this?

**Comment by venkygot** [comment] 2020-07-27 06:33
@callmekatootie yes i'm able to reproduce it, working on the fixes. Keep you posted shortly

**Comment by cwdcwd** [comment] 2020-07-27 16:21
Payment task has been updated: https://software.topcoder.com/review/actions/ViewProjectDetails?pid=30134112<br/><br/>```This is an automated message for lazybaer via Topcoder X```

**Closed** 2020-07-27 16:21 UTC
Labels: bug, low priority, tcx_Assigned, tcx_FixAccepted
