### ISSUE TITLE
In "Add to Group" click on "+Create" does no action

### ISSUE THREAD

**Issue by coderkid19** [topcoder-platform/u-bahn-app#61] opened 2020-07-12 13:26 UTC
Steps:
1)Login to portal https://skill-search.topcoder-dev.com/ with tonyj/appirio123  ( selected Org topcoder)
2) For user "Augusta Torp" click on "+" sign from home page
3) "Add to Group" popup opened.
4)  click on "+Create" 
Observe

Current Result :
In "Add to Group" click on "+Create" does no action

Expected result:
In "Add to Group" click on "+Create" should do action accordingly.

Latest Chrome
Windows 10

**Comment by coderkid19** [comment] 2020-07-12 13:27
![Chrome_Version_83 0 4103 116](https://user-images.githubusercontent.com/51490878/87247424-669af000-c471-11ea-924b-3fe7262776fc.png)

![4](https://user-images.githubusercontent.com/51490878/87247438-7b778380-c471-11ea-9930-80f00cf389ee.png)


![Windows10_version](https://user-images.githubusercontent.com/51490878/87247440-7e727400-c471-11ea-8711-09175b58e85f.png)

**Comment by callmekatootie** [comment] 2020-07-15 07:28
duplicate of #21

**Closed by callmekatootie** 2020-07-15 07:28 UTC
