### ISSUE TITLE
Add Filter model buttons are hidden

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/u-bahn-app#42] opened 2020-07-12 13:19 UTC
**Reproduction Steps:**

1. Open the Application https://skill-search.topcoder-dev.com/
2. Click Topcoder > Go to first tab
3. Click 'Add Filter' Check the buttons

**Actual Result:** Add Filter model buttons are hidden

**Expected Result:** Should display the buttons

**Device/OS:** Laptop | Windows 10 (64bit)

**Browser Information:** Chrome 83.0.4103.116 | Firefox 78.0.2 | IE11

**Comment by codejamtc** [comment] 2020-07-12 13:19
![image](https://user-images.githubusercontent.com/42398485/87247272-733f2a00-c418-11ea-9803-84fc417d9ed7.png)

**Comment by callmekatootie** [comment] 2020-07-15 06:47
duplicate of #17 - this one's the filter modal, but same reason

**Closed by callmekatootie** 2020-07-15 06:47 UTC
