### ISSUE TITLE
Not Able To Create Group With 1 Letter. Its Showing Message As Creating......

### ISSUE THREAD

**Issue by devsreekrishna** [topcoder-platform/u-bahn-app#266] opened 2020-07-12 15:14 UTC
1. Go To https://skill-search.topcoder-dev.com/

2. Select Topcoder

3. Click On Icon Next To Filter

4. Click On Search Or Create Group & Type One Letter Then Click Create & Observe.

5. See Screencast & Screenshot:-
[12.mp4.zip](https://github.com/topcoder-platform/u-bahn-app/files/4908729/12.mp4.zip)
![12](https://user-images.githubusercontent.com/42583358/87250086-6b1ad500-c480-11ea-969e-b9c7d61994e1.png)

6. Current Result:- Not Able To Create Group With 1 Letter. Its Showing Message As Creating......

7. Expected Result:- Should Be Able To Create Group.

8. Browser Version:- Google Chrome Version 83.0.4103.116 (Official Build) (64-bit)

9. OS Version:- macOS High Sierra Version 10.13.6 (17G12034)

**Comment by callmekatootie** [comment] 2020-07-16 15:07
duplicate of #116

**Closed by callmekatootie** 2020-07-16 15:07 UTC
