### ISSUE TITLE
'COMPANY ATTRIBUTES' Filters textboxes don't have a clear icon

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/u-bahn-app#304] opened 2020-07-12 15:44 UTC
https://take.ms/dyQcK

**Reproduction Steps:**

1. Open the Application https://skill-search.topcoder-dev.com/
2. Click Topcoder > Go to the Tab 01 (Search)
3. Add all the 'COMPANY ATTRIBUTES' from Add Filters
4. Type some text on those and check the textbox

**Actual Result:** 'COMPANY ATTRIBUTES' Filters textboxes don't have a clear icon

**Expected Result:** Should have a clear button to clear the text

**Device/OS:** Laptop | Windows 10 (64bit)

**Browser Information:** Chrome 83.0.4103.116 | Firefox 78.0.2 | IE11

**Comment by callmekatootie** [comment] 2020-07-17 15:52
duplicate of #161

**Closed by callmekatootie** 2020-07-17 15:52 UTC
