### ISSUE TITLE
Recently created group is not showing, in add group to user profile

### ISSUE THREAD

**Issue by rajanmourya** [topcoder-platform/u-bahn-app#277] opened 2020-07-12 15:20 UTC
**Describe the bug**
Recently created group is not showing, in add group to user profile

**To Reproduce**
1. Go to https://skill-search.topcoder-dev.com/
2. Now go to group
3. Now create one group
4. Now click on + icon in user profile to add group and search the group recently created 

**Actual Behavior**
Observe the group is not showing over there

**Expected behavior**
Group must show in adding the user profile

**Screenshots**
[2020-07-12 19-41-38.zip](https://github.com/topcoder-platform/u-bahn-app/files/4908748/2020-07-12.19-41-38.zip)

**OS/Browser:**
  - OS:  Windows 10 (64 Bit)
 - Browser: IE 11
 - Version:  11.900

**Comment by callmekatootie** [comment] 2020-07-16 15:22
duplicate of #187

**Closed by callmekatootie** 2020-07-16 15:22 UTC
