### ISSUE TITLE
Able to create group with same name as existing group

### ISSUE THREAD

**Issue by coderkid19** [topcoder-platform/u-bahn-app#322] opened 2020-07-12 16:03 UTC
Steps:
1)Login to portal https://skill-search.topcoder-dev.com/ with tonyj/appirio123  ( selected Org topcoder)
2) Click on Middle Tab.
3) Search an existing Group say "House Stark"
4) Observe

Current Result :
Able to create group with same name as existing group

Expected result:
Should not be able to create group with existing name

Latest Chrome
Windows 10

**Comment by coderkid19** [comment] 2020-07-12 16:05
![30](https://user-images.githubusercontent.com/51490878/87251196-758c9d00-c487-11ea-9444-61b6cf136399.png)


![Firefox_version_77 0 2](https://user-images.githubusercontent.com/51490878/87251205-86d5a980-c487-11ea-95f4-b68de4af9fc1.png)

**Comment by coderkid19** [comment] 2020-07-12 16:05
![Chrome_Version_83 0 4103 116](https://user-images.githubusercontent.com/51490878/87251214-9523c580-c487-11ea-8870-45fe075fe1df.png)

**Comment by callmekatootie** [comment] 2020-07-17 06:44
duplicate of #93

**Closed by callmekatootie** 2020-07-17 06:44 UTC
