### ISSUE TITLE
cant see done button on filter page

### ISSUE THREAD

**Issue by akultalwar89** [topcoder-platform/u-bahn-app#52] opened 2020-07-12 13:23 UTC
Steps to reproduce
• 1. Go to application-https://skill-search.topcoder-dev.com/
• 2. scroll down and click on Add filter page, cant see done button to close

Current results
 scroll down and click on Add filter page, cant see done button to close

Expected results

cant see done or cancel button to close, should be visible

• Browser version: Chrome: Version 83.0.4103.116
• OS version : Macbook Air , Catalina 10.15.2
Screen shots

**Comment by akultalwar89** [comment] 2020-07-12 13:23
![Screen Shot 2020-07-12 at 6 52 12 PM](https://user-images.githubusercontent.com/57220292/87247330-eeccc580-c470-11ea-9df1-74acb76de1fa.png)

**Comment by callmekatootie** [comment] 2020-07-15 07:08
Duplicate of #17

**Closed by callmekatootie** 2020-07-15 07:08 UTC

**Comment by akultalwar89** [comment] 2020-07-17 14:29
Hi @callmekatootie - They both are different pages. one is Edit screen, and this one Filter page - developer will be fixing the issues separately?

**Comment by callmekatootie** [comment] 2020-07-17 16:22
Treating that as an issue with all modals

**Comment by akultalwar89** [comment] 2020-07-17 16:23
@callmekatootie  - sure Thanks Mithun
