### ISSUE TITLE
[Bug Hunt]:No option to close the profile once user have clicked on edit button

### ISSUE THREAD

**Issue by komal123s** [topcoder-platform/u-bahn-app#264] opened 2020-07-12 15:14 UTC
**Steps:**
1.Navigate to https://skill-search.topcoder-dev.com/
2.Navigate to Groups tab
![image](https://user-images.githubusercontent.com/68163678/87250015-f47dd780-c47f-11ea-8c5c-32375fff38a6.png)
3.Click on Edit button of any profile.
![image](https://user-images.githubusercontent.com/68163678/87250043-255e0c80-c480-11ea-8131-792163b108a7.png)
4. Verify there is no option for closing the profile.

**Actual result:**
No close icon is displayed
**Expected result:**
There should be close icon for user to close the profile.

**Device/Browser/OS:**
Laptop
Google Chrome(Version 83.0.4103.116)
Windows10

**Comment by komal123s** [comment] 2020-07-12 18:21
Data Used:
tonyj\appirio123

**Comment by callmekatootie** [comment] 2020-07-16 15:06
duplicate of #17

**Closed by callmekatootie** 2020-07-16 15:06 UTC
