### ISSUE TITLE
Dropdowns dont close on outside click

### ISSUE THREAD

**Issue by g1tman** [topcoder-platform/u-bahn-app#69] opened 2020-07-12 13:30 UTC
## Steps to Reproduce

    1. Open the URL https://skill-search.topcoder-dev.com/ and login
    2. Select some filter and get results
    3. Open dropdowns (One on top right - username, Other to select filters of results)
    4. Click elsewhere outside both dropdown

## Screenshots/Video
![Screenshot from 2020-07-12 18-57-55](https://user-images.githubusercontent.com/32861951/87247516-e2953800-c471-11ea-8732-1782db56033f.png)

##  Actual Result(s)

Dropdown Dialog doesnt close

##  Expected Result(s)

Dropdown dialog should close on outside click

##  Environment Details

    Browser(s): Firefox 78.0.1 (64-bit)

**Comment by callmekatootie** [comment] 2020-07-15 07:37
duplicate of #45

**Closed by callmekatootie** 2020-07-15 07:37 UTC

**Comment by g1tman** [comment] 2020-07-15 10:29
@callmekatootie this issue also highlights about sort drop-down also.

Which is same as #102 (raised after this)

**Comment by callmekatootie** [comment] 2020-07-15 15:16
I do not see in your original description any mention of sort drop down. I am afraid I cannot consider it now (also - only 1 issue per ticket)

**Comment by g1tman** [comment] 2020-07-15 15:48
@callmekatootie it's mentioned in step 3. And also shown in screenshot.

Isn't it adviced to make issues generic if issue is common. Steps of reproduction and details are common for both drop-downs.

Also, this issue is before both the mentioned issues. 102 and 73.

**Comment by callmekatootie** [comment] 2020-07-16 14:36
I am afraid my decision stands
