### ISSUE TITLE
[Bug Hunt] Content overflows from the place

### ISSUE THREAD

**Issue by HardikJ7321** [topcoder-platform/u-bahn-app#153] opened 2020-07-12 14:05 UTC
Displayed user profile content overflows the box and hindering other profile boxes.
![overflow](https://user-images.githubusercontent.com/44543811/87248206-d612de80-c475-11ea-8ec6-8e2438d87bf6.png)

**Comment by callmekatootie** [comment] 2020-07-15 11:00
duplicate of #91

**Closed by callmekatootie** 2020-07-15 11:00 UTC
