### ISSUE TITLE
Totally different results if the keyword has space

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/u-bahn-app#229] opened 2020-07-12 14:52 UTC
https://take.ms/tVu64

**Reproduction Steps:**

1. Open the Application https://skill-search.topcoder-dev.com/
2. Click Topcoder > Go to the Tab 01
3. Enter 'Maryamd' to Search
4. Enter 'Maryamd ' to Search

**Actual Result:** Totally different results if the keyword has space

**Expected Result:** Should display only Maryamd in both instances. Some records are not nearly matched with the entered ketword

**Device/OS:** Laptop | Windows 10 (64bit)

**Browser Information:** Chrome 83.0.4103.116 | Firefox 78.0.2 | IE11

**Comment by callmekatootie** [comment] 2020-07-15 14:06
will accept as a bug. need to trim search text

**Comment by callmekatootie** [comment] 2020-07-17 15:55
duplicate of #150 actually

**Closed by callmekatootie** 2020-07-17 15:55 UTC
Labels: bug
