### ISSUE TITLE
Underline straight-line not shown when "First name", "Last name", "Current role", "Company", "Location" are filled with values 

### ISSUE THREAD

**Issue by coderkid19** [topcoder-platform/u-bahn-app#309] opened 2020-07-12 15:49 UTC
Steps:
1)Login to portal https://skill-search.topcoder-dev.com/ with tonyj/appirio123  ( selected Org topcoder)
2) Click on Edit icon for any user say Dipsoco Casper
3) "First name", "Last name", "Current role", "Company", "Location" are filled with values 
4) Observe the underline  straight-line below the values

Current Result :
Underline straight-line not shown when "First name", "Last name", "Current role", "Company", "Location" are filled with values 

Expected result:
Underline straight-line should be shown when "First name", "Last name", "Current role", "Company", "Location" are filled with values 

Latest Chrome
Windows 10

**Comment by coderkid19** [comment] 2020-07-12 15:51
![29](https://user-images.githubusercontent.com/51490878/87250877-a370e200-c485-11ea-8836-c64998d5dd93.png)

![Firefox_version_77 0 2](https://user-images.githubusercontent.com/51490878/87250885-acfa4a00-c485-11ea-8549-75f7b8fcb5d2.png)

![Chrome_Version_83 0 4103 116](https://user-images.githubusercontent.com/51490878/87250886-af5ca400-c485-11ea-872b-c1b8e5f6d482.png)

**Comment by callmekatootie** [comment] 2020-07-17 06:30
duplicate of #41

**Closed by callmekatootie** 2020-07-17 06:30 UTC
