### ISSUE TITLE
Alignment at top is not correct for the edit talent screen. Buttons at the top is not visible completely 

### ISSUE THREAD

**Issue by ajithck333** [topcoder-platform/u-bahn-app#31] opened 2020-07-12 13:14 UTC
Device: Laptop

Operating System: Windows 10

Browser:Chrome

Steps to reproduce :

1.	Log in to https://skill-search.topcoder-dev.com/

2.	Click on the edit talent screen. Edit pop up is not loaded correctly. Alignment at the top is not correct. Buttons at the top is not visible completely 

Actual result:

Alignment at the top is not correct. Buttons at the top is not visible completely 

Expected results: 

Page should be completly visible 
[edit screen - alignment at top is not correct.docx](https://github.com/topcoder-platform/u-bahn-app/files/4908542/edit.screen.-.alignment.at.top.is.not.correct.docx)

**Comment by callmekatootie** [comment] 2020-07-15 05:53
Duplicate of #17

**Closed by callmekatootie** 2020-07-15 05:53 UTC
