### ISSUE TITLE
Seems lot of space below the edit profile popup

### ISSUE THREAD

**Issue by Krishna1507** [topcoder-platform/u-bahn-app#350] opened 2020-07-12 16:57 UTC
**Steps to reproduce**

1. Open the application https://skill-search.topcoder-dev.com/ and login
2. Go to topcoder and tap on first tab
3. Tap on edit icon of profile and observe the popup page

**Actual Result:** 
Seems use less space below the edit profile popup

**Expected Result:** 
Should not useless space in popup UI, content should be aligned 

**Screenshot**
![image](https://user-images.githubusercontent.com/23450398/87252210-d2d81c80-c48e-11ea-9b38-b87d8c05ae39.png)

**Device/OS:**  Think-pad | Windows 10 (64bit) 

**Browser Information:** IE11 11.329.19041.0

**Comment by callmekatootie** [comment] 2020-07-17 07:43
duplicate of #340

**Closed by callmekatootie** 2020-07-17 07:43 UTC
