### ISSUE TITLE
Search or create group large name UI issue

### ISSUE THREAD

**Issue by Krishna1507** [topcoder-platform/u-bahn-app#335] opened 2020-07-12 16:25 UTC
**Steps to reproduce**

1. Open the application https://skill-search.topcoder-dev.com/ and login
2. Go to topcoder and go to the second tab
3. type large char in search or create group box and created
4. Observe large group name 

**Actual Result:** 
Search or create group large name UI issue 

**Expected Result:** 

Large group name should trunked from end

**Screenshot**
[Bug11.zip](https://github.com/topcoder-platform/u-bahn-app/files/4908827/Bug11.zip)

**Device/OS:**  Think-pad | Windows 10 (64bit) 

**Browser Information:** IE11 11.329.19041.0

**Comment by callmekatootie** [comment] 2020-07-17 15:06
duplicate of #152

**Closed by callmekatootie** 2020-07-17 15:06 UTC
