### ISSUE TITLE
Unable to differentiate between "GENERAL ATTRIBUTES" and "COMPANY ATTRIBUTES" in filters.

### ISSUE THREAD

**Issue by coderkid19** [topcoder-platform/u-bahn-app#149] opened 2020-07-12 14:03 UTC
Steps:
1)Login to portal https://skill-search.topcoder-dev.com/ with tonyj/appirio123  ( selected Org topcoder)
2) Click on "Add filters" from left bottom 
3) Enable all filters in "GENERAL ATTRIBUTES" and "COMPANY ATTRIBUTES" from Add filters
4) Observe two "Location"

Current Result :
Unable to differentiate between "GENERAL ATTRIBUTES" and "COMPANY ATTRIBUTES" in filters.
User may feel it is duplicate 

Expected result:
Should be able to differentiate between "GENERAL ATTRIBUTES" and "COMPANY ATTRIBUTES" in filters.

Latest Firefox/Chrome
Windows 10

**Comment by coderkid19** [comment] 2020-07-12 14:04
![12_1](https://user-images.githubusercontent.com/51490878/87248364-b8924480-c476-11ea-9912-385337d819f1.png)

![12_2](https://user-images.githubusercontent.com/51490878/87248365-b9c37180-c476-11ea-95d3-eaa67107fb98.png)

![Chrome_Version_83 0 4103 116](https://user-images.githubusercontent.com/51490878/87248369-bcbe6200-c476-11ea-830e-4cbc31cb83de.png)

![Windows10_version](https://user-images.githubusercontent.com/51490878/87248371-be882580-c476-11ea-8bd9-5e0d4e52e70d.png)

**Comment by callmekatootie** [comment] 2020-07-15 10:58
Valid bug. Perhaps we hide Location from custom attribute filters... :thinking:

**Comment by callmekatootie** [comment] 2020-07-17 15:49
This is now a duplicate of #85 which will be dealing with conflicting attributes

**Closed by callmekatootie** 2020-07-17 15:49 UTC
Labels: bug
