### ISSUE TITLE
No Scroll bar when user click on edit profile Hence unable to cancel Edit profile page

### ISSUE THREAD

**Issue by coderkid19** [topcoder-platform/u-bahn-app#18] opened 2020-07-12 13:08 UTC
Steps :

1) Login to portal https://skill-search.topcoder-dev.com/ with tonyj/appirio123
2) Click on Edit icon on any profile.
3) Edit profile page open
4) Ensure that browser has 100% viewing
Observe

Current result:
Unable to see the cancel button.
Need to reduce browser viewing to 80% or less

Expected result:
Should have scroll bar so that user need not change view.

**Comment by coderkid19** [comment] 2020-07-12 13:10
![Firefox_version_77 0 2](https://user-images.githubusercontent.com/51490878/87247058-f9865b00-c46e-11ea-8698-27e9d0772964.png)
![Windows10_version](https://user-images.githubusercontent.com/51490878/87247059-fbe8b500-c46e-11ea-95c1-8a75fd40a40b.png)
![1](https://user-images.githubusercontent.com/51490878/87247076-276b9f80-c46f-11ea-838a-088ebd9447a4.png)

**Comment by callmekatootie** [comment] 2020-07-15 05:31
Duplicate of #17

**Closed by callmekatootie** 2020-07-15 05:31 UTC
