### ISSUE TITLE
Still allow create group name is space characters

### ISSUE THREAD

**Issue by HongHT** [topcoder-platform/u-bahn-app#306] opened 2020-07-12 15:46 UTC
**Reproduction Steps:**
1. Open the application 
2. On "Search" tab, click on "+" icon then enter some spaces in textbox 
3. Click on "Create" button and observe the result

**Screenshot/screencast:**
https://drive.google.com/drive/folders/1gcGYOc37iO3JDV5KumLxNNWHbF0nMas3?fbclid=IwAR2pD3gYGvZcsncY7T4ewgF1IEi-61WkcDjy_Rs7N6WIH86KnWvGCSpOFdU

**Actual Result:** Still allow create group name is space characters

**Expected Result:** Should not create group name is space characters.

**Device/OS:** Laptop | Windows 10 (64bit)

**Browser Information:** IE11 , Google Chrome 83.0.4103.116, Firefox 78.0.2

**Comment by callmekatootie** [comment] 2020-07-16 15:47
duplicate of #34

**Closed by callmekatootie** 2020-07-16 15:47 UTC
