### ISSUE TITLE
[Bug Hunt] Creating a Group in Main Screen successfully but not showing up when we need to add it to Profile for User

### ISSUE THREAD

**Issue by greenmug-md** [topcoder-platform/u-bahn-app#499] opened 2020-07-14 03:41 UTC
<img width="1270" alt="Screenshot 2020-07-14 at 9 09 01 AM" src="https://user-images.githubusercontent.com/34758872/87381269-e8923280-c5b1-11ea-9a57-f8a78246dd53.png">

Reproduction Steps:
	1.	Open the Application https://skill-search.topcoder-dev.com/
	2.	Click Topcoder > Go to the Tab 02 (Groups)
	3.	Click on “My Groups” ,
	4.	Create a Group with “London New York”
	5.	Click on a Profile to add the filter , it does not show while searching 
	
Expected Result: Group should be available to be added to user profile

Device/OS: Laptop | MACOS  (64bit)
Browser Information: Chrome 83.0.4103.116 | Firefox 78.0.2 | IE11

**Comment by callmekatootie** [comment] 2020-07-17 13:22
duplicate of #187

**Closed by callmekatootie** 2020-07-17 13:22 UTC
