### ISSUE TITLE
The page should scroll to top when go to another page

### ISSUE THREAD

**Issue by HongHT** [topcoder-platform/u-bahn-app#160] opened 2020-07-12 14:07 UTC
**Reproduction Steps:**
1. Open the application: https://skill-search.topcoder-dev.com/
2. Scroll down page -> click on next page number
3. Observe result

**Screenshot/screencast:**
https://drive.google.com/drive/folders/1GJhkW62_AvXqNKGmoTrEBURybhKMBVbu

**Actual Result:** The page doesn't scroll to top when go to another page

**Expected Result:** The page should scroll to top when go to another page

**Device/OS:** Laptop | Windows 10 (64bit)

**Browser Information:** IE11 , Google Chrome 83.0.4103.116, Firefox 78.0.2

**Comment by callmekatootie** [comment] 2020-07-15 11:22
duplicate of #66

**Closed by callmekatootie** 2020-07-15 11:22 UTC
