### ISSUE TITLE
[Bug Hunt]Scrolling controls not available on IE browser

### ISSUE THREAD

**Issue by komal123s** [topcoder-platform/u-bahn-app#393] opened 2020-07-12 18:49 UTC
**Steps:**
1.Navigate to https://skill-search.topcoder-dev.com/

2.Login with data.
![image](https://user-images.githubusercontent.com/68163678/87254070-9233cf80-c49d-11ea-9df1-0719e32148e8.png)

3.Click on Edit button of any profile.
![image](https://user-images.githubusercontent.com/68163678/87254106-d45d1100-c49d-11ea-8eaf-f7f841b9e60d.png)

4.Verify scrolling control for user to scroll up and down the profile section is missing
![image](https://user-images.githubusercontent.com/68163678/87254143-0b332700-c49e-11ea-83ab-4bb8ae2731ee.png)

**Actual result:**
Scrolling control is missing in IE browser
**Expected result:**
Scrolling controls should be given to user same as Chrome browser
![image](https://user-images.githubusercontent.com/68163678/87254160-3289f400-c49e-11ea-8936-951bb314ba4c.png)

**Device/Browser/OS:**
Laptop
IE 11 (Version:11.0.9600.19400)
Windows10

**Login credential used:**
tonyj\appirio123

**Comment by callmekatootie** [comment] 2020-07-17 15:23
duplicate of #17

**Closed by callmekatootie** 2020-07-17 15:23 UTC
