### ISSUE TITLE
Different height displayed in each occasion when user types text to the text field and removes it in "Add Group" dialog 

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/u-bahn-app#352] opened 2020-07-12 17:01 UTC
https://monosnap.com/file/RHtX0joDVIBgClNSSnutehJTnsy6RD

**Reproduction Steps:**

1. Open the Application https://skill-search.topcoder-dev.com/
2. Click Topcoder > Go to the Tab 01 (Search)
3. Click Add Group and Type "sadasdsadasdsadsadsadd"
4. Click Clear button
5. Enter 'asdasdasdasdasdasd'
6. Click Clear button
7. Enter 'asdasdasdasdasdasd'
8. Click Clear button

**Actual Result:** Different height displayed in each occasion when user types text to the text field and removes it in "Add Group" dialog 

**Expected Result:** Should be consistent

**Device/OS:** Laptop | Windows 10 (64bit)

**Browser Information:**  IE11

**Comment by callmekatootie** [comment] 2020-07-17 07:44
duplicate of #336

**Closed by callmekatootie** 2020-07-17 07:44 UTC
