### ISSUE TITLE
[Bug Hunt] Deactivate button is hidden

### ISSUE THREAD

**Issue by komal123s** [topcoder-platform/u-bahn-app#270] opened 2020-07-12 15:17 UTC
**Steps:**
1.Navigate to https://skill-search.topcoder-dev.com/
2.Navigate to Groups tab
![image](https://user-images.githubusercontent.com/68163678/87250015-f47dd780-c47f-11ea-8c5c-32375fff38a6.png)
3.Click on Edit button of "Myles Connelly" profile.
![image](https://user-images.githubusercontent.com/68163678/87250131-a4534500-c480-11ea-9112-494168066bd0.png)

4. Verify Deactivate button is hidden

**Actual result:**
Deactivate button is hidden
**Expected result:**
Deactivate button should not be hidden
**Device/Browser/OS:**
Laptop
Google Chrome(Version 83.0.4103.116)
Windows10

**Comment by komal123s** [comment] 2020-07-12 18:20
Data Used:
tonyj\appirio123

**Comment by callmekatootie** [comment] 2020-07-16 15:10
duplicate of #17

**Closed by callmekatootie** 2020-07-16 15:10 UTC
