### ISSUE TITLE
While Try To Create Group With One Letter, Console Is Showing Error

### ISSUE THREAD

**Issue by devsreekrishna** [topcoder-platform/u-bahn-app#257] opened 2020-07-12 15:06 UTC
1. Go To https://skill-search.topcoder-dev.com/

2. Select Topcoder

3. Click Next To Filter Icon

4. Click Search Or Create Group > Type One Letter > Click On Create Then Observe In Console.

5. See Screencast & Screenshot:-
[11.mp4.zip](https://github.com/topcoder-platform/u-bahn-app/files/4908717/11.mp4.zip)
![11](https://user-images.githubusercontent.com/42583358/87249859-39edd500-c47f-11ea-956c-0532a19a9372.png)

6. Current Result:- While Try To Create Group With One Letter, Console Is Showing Error

7. Expected Result:- While Try To Create Group With One Letter, Console Should Not Show Any Error

8. Browser Version:- Google Chrome Version 83.0.4103.116 (Official Build) (64-bit)

9. OS Version:- macOS High Sierra Version 10.13.6 (17G12034)

**Comment by callmekatootie** [comment] 2020-07-15 14:44
duplicate of #116

**Closed by callmekatootie** 2020-07-15 14:44 UTC
