### ISSUE TITLE
Changing a page should scroll to the top of the content

### ISSUE THREAD

**Issue by rprakash20** [topcoder-platform/u-bahn-app#83] opened 2020-07-12 13:36 UTC
### Steps to Reproduce
Open https://skill-search.topcoder-dev.com/ web app
Login with tonyj /appirio123
Scroll down to the pagination controls
Click on page 2 to move to page 2
Notice the content after the page loads

### Screenshots or Screen Capture

[pagination.mov.zip](https://github.com/topcoder-platform/u-bahn-app/files/4908578/pagination.mov.zip)

### Current Results
User has to scroll the content to move to the top after changing page number

### Expected Results
Changing a page should scroll to the top of the content

### Browser version and OS version
- Device: MacBook Pro 13 inch
- Browser: Chrome Version 83.0.4103.116 (Official Build) (64-bit)
- OS Version: macOS Catalina 10.15.4

**Comment by callmekatootie** [comment] 2020-07-15 07:57
duplicate of #66

**Closed by callmekatootie** 2020-07-15 07:57 UTC
