### ISSUE TITLE
[Common] Can't add a group 

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/u-bahn-app#167] opened 2020-07-12 14:10 UTC
![image](https://user-images.githubusercontent.com/42398485/87248540-8d303b00-c41f-11ea-8773-7767e18cb433.png)

**Reproduction Steps:**

1. Open the Application https://skill-search.topcoder-dev.com/
2. Click Topcoder > Go to the Tab 01 or Tab 02
3. Click Add Group Icon
4. Enter a Name
5. Click Save

```
/api/skills?q=dsf:1 Failed to load resource: the server responded with a status of 500 ()
09:08:52.135 createError.js:16 Uncaught (in promise) Error: Request failed with status code 500
    at e.exports (createError.js:16)
    at e.exports (settle.js:17)
    at XMLHttpRequest.d.onreadystatechange (xhr.js:61)
09:08:52.135 createError.js:16 Uncaught (in promise) Error: Request failed with status code 500
    at e.exports (createError.js:16)
    at e.exports (settle.js:17)
    at XMLHttpRequest.d.onreadystatechange (xhr.js:61)
09:08:52.212 /api/skills?q=dsfdsfdsf:1 Failed to load resource: the server responded with a status of 500 ()
09:08:52.215 createError.js:16 Uncaught (in promise) Error: Request failed with status code 500
    at e.exports (createError.js:16)
    at e.exports (settle.js:17)
    at XMLHttpRequest.d.onreadystatechange (xhr.js:61)
09:09:00.353 api.topcoder-dev.com/v5/groups:1 Failed to load resource: the server responded with a status of 400 ()
09:09:00.362 groups.js:192 Error: Request failed with status code 400
    at e.exports (createError.js:16)
    at e.exports (settle.js:17)
    at XMLHttpRequest.d.onreadystatechange (xhr.js:61)
09:09:00.363 groups.js:196 Uncaught (in promise) TypeError: Cannot read property 'data' of undefined
    at groups.js:196
    at c (runtime.js:45)
    at Generator._invoke (runtime.js:274)
    at Generator.forEach.e.<computed> [as throw] (runtime.js:97)
    at r (asyncToGenerator.js:3)
    at c (asyncToGenerator.js:29)
```

**Actual Result:** Can't add a group 

**Expected Result:** Should be able to add a group

**Device/OS:** Laptop | Windows 10 (64bit)

**Browser Information:** Chrome 83.0.4103.116 | Firefox 78.0.2 | IE11

**Comment by callmekatootie** [comment] 2020-07-15 11:54
duplicate of #116

**Closed by callmekatootie** 2020-07-15 11:54 UTC
