### ISSUE TITLE
"Add Filters" Options are not vertically aligned

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/u-bahn-app#238] opened 2020-07-12 14:58 UTC
![image](https://user-images.githubusercontent.com/42398485/87249695-2bbf9a80-c426-11ea-8988-ebfc29ab22e6.png)

**Reproduction Steps:**

1. Open the Application https://skill-search.topcoder-dev.com/
2. Click Topcoder > Go to the Tab 01
3. Click "Add Filters"
4. Check the items

**Actual Result:** "Add Filters" Options are not vertically aligned

**Expected Result:** Should align properly

**Device/OS:** Laptop | Windows 10 (64bit)

**Browser Information:** IE11

**Comment by callmekatootie** [comment] 2020-07-15 14:26
valid bug

**Comment by callmekatootie** [comment] 2020-07-17 15:56
duplicate of #118 actually

**Closed by callmekatootie** 2020-07-17 15:56 UTC
Labels: bug
