### ISSUE TITLE
While Clicking Logout Its Showing Message As Ok

### ISSUE THREAD

**Issue by devsreekrishna** [topcoder-platform/u-bahn-app#77] opened 2020-07-12 13:33 UTC
1. Go To https://skill-search.topcoder-dev.com/

2. Select Topcoder 

3. Then Go Near TonyJ (Topcoder) & Select Logout Then Observe.

4. See Screencast & Screenshot:-
[3.mp4.zip](https://github.com/topcoder-platform/u-bahn-app/files/4908571/3.mp4.zip)
![3](https://user-images.githubusercontent.com/42583358/87247572-36078600-c472-11ea-91c5-9a751e9ed58a.png)

5. Current Result:- While Clicking Logout Its Showing Message As Ok

6. Expected Result:- While Clicking Logout It Should Show Message As You Have Successfully logout Like This

7. Browser Version:- Google Chrome Version 83.0.4103.116 (Official Build) (64-bit)

8. OS Version:- macOS High Sierra Version 10.13.6 (17G12034)

**Comment by callmekatootie** [comment] 2020-07-15 07:48
duplicate of #63

**Closed by callmekatootie** 2020-07-15 07:48 UTC

**Comment by devsreekrishna** [comment] 2020-07-16 16:47
Hi

I Want To Say OK Button Should Not Be In Left Of Screen. It Should Be In Middle Of Screen.

Thanks

**Comment by callmekatootie** [comment] 2020-07-17 16:44
Ok - In which case this is not a valid issue. The page that displays OK is not part of the app (see the url)

**Comment by callmekatootie** [comment] 2020-07-17 16:44
It basically comes from our auth provider and we have no control over it (we do - and that is where #63 comes)
